MODULE CLN1MODULE
  IMPLICIT NONE
  INTEGER,SAVE,POINTER :: NCLN
  INTEGER,SAVE,POINTER :: ICLNCB
  INTEGER,SAVE,POINTER :: ICLNHD
  INTEGER,SAVE,POINTER :: ICLNDD
  INTEGER,SAVE,POINTER :: ICLNIB
  INTEGER,SAVE,POINTER :: NCLNNDS
  INTEGER,SAVE,POINTER :: NCLNGWC
  INTEGER,SAVE,POINTER :: NCONDUITYP
  INTEGER,SAVE,DIMENSION(:),POINTER :: NNDCLN
  INTEGER,SAVE,DIMENSION(:),POINTER :: IFLINCLN
  INTEGER,SAVE,DIMENSION(:),POINTER :: ICCWADICLN
  INTEGER,SAVE,DIMENSION(:),POINTER :: ICGWADICLN
  INTEGER,SAVE,DIMENSION(:),POINTER :: CLNCON
  REAL,SAVE,DIMENSION(:,:),POINTER :: ACLNNDS
  REAL,SAVE,DIMENSION(:,:),POINTER :: ACLNGWC
  REAL,SAVE,DIMENSION(:,:),POINTER :: ACLNCOND
  DOUBLE PRECISION,SAVE,POINTER,DIMENSION(:) :: HWADICC
  DOUBLE PRECISION,SAVE,POINTER,DIMENSION(:) :: HWADICG
  DOUBLE PRECISION,SAVE,POINTER,DIMENSION(:) :: DWADICC
  DOUBLE PRECISION,SAVE,POINTER,DIMENSION(:) :: DWADICG
  TYPE :: CLNGLOTYPE
    INTEGER,POINTER :: NCLN
    INTEGER,POINTER :: ICLNCB
    INTEGER,POINTER :: ICLNHD
    INTEGER,POINTER :: ICLNDD
    INTEGER,POINTER :: ICLNIB
    INTEGER,POINTER :: NCLNNDS
    INTEGER,POINTER :: NCLNGWC
    INTEGER,POINTER :: NCONDUITYP
    INTEGER,DIMENSION(:),POINTER :: NNDCLN
    INTEGER,DIMENSION(:),POINTER :: IFLINCLN
    INTEGER,DIMENSION(:),POINTER :: ICCWADICLN
    INTEGER,DIMENSION(:),POINTER :: ICGWADICLN
    INTEGER,DIMENSION(:),POINTER :: CLNCON
    REAL,DIMENSION(:,:),POINTER :: ACLNNDS
    REAL,DIMENSION(:,:),POINTER :: ACLNGWC
    REAL,DIMENSION(:,:),POINTER :: ACLNCOND
    DOUBLE PRECISION,POINTER,DIMENSION(:) :: HWADICC
    DOUBLE PRECISION,POINTER,DIMENSION(:) :: HWADICG
    DOUBLE PRECISION,POINTER,DIMENSION(:) :: DWADICC
    DOUBLE PRECISION,POINTER,DIMENSION(:) :: DWADICG
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE CLNGLOTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(CLNGLOTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%NCLN)
    DEALLOCATE(THIS%ICLNCB)
    DEALLOCATE(THIS%ICLNHD)
    DEALLOCATE(THIS%ICLNDD)
    DEALLOCATE(THIS%ICLNIB)
    DEALLOCATE(THIS%NCLNNDS)
    DEALLOCATE(THIS%NCLNGWC)
    DEALLOCATE(THIS%NCONDUITYP)
    DEALLOCATE(THIS%NNDCLN)
    DEALLOCATE(THIS%IFLINCLN)
    DEALLOCATE(THIS%ICCWADICLN)
    DEALLOCATE(THIS%ICGWADICLN)
    DEALLOCATE(THIS%CLNCON)
    DEALLOCATE(THIS%ACLNNDS)
    DEALLOCATE(THIS%ACLNGWC)
    DEALLOCATE(THIS%ACLNCOND)
    DEALLOCATE(THIS%HWADICC)
    DEALLOCATE(THIS%HWADICG)
    DEALLOCATE(THIS%DWADICC)
    DEALLOCATE(THIS%DWADICG)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(CLNGLOTYPE),INTENT(INOUT) :: THIS
    THIS%NCLN=>NCLN
    THIS%ICLNCB=>ICLNCB
    THIS%ICLNHD=>ICLNHD
    THIS%ICLNDD=>ICLNDD
    THIS%ICLNIB=>ICLNIB
    THIS%NCLNNDS=>NCLNNDS
    THIS%NCLNGWC=>NCLNGWC
    THIS%NCONDUITYP=>NCONDUITYP
    THIS%NNDCLN=>NNDCLN
    THIS%IFLINCLN=>IFLINCLN
    THIS%ICCWADICLN=>ICCWADICLN
    THIS%ICGWADICLN=>ICGWADICLN
    THIS%CLNCON=>CLNCON
    THIS%ACLNNDS=>ACLNNDS
    THIS%ACLNGWC=>ACLNGWC
    THIS%ACLNCOND=>ACLNCOND
    THIS%HWADICC=>HWADICC
    THIS%HWADICG=>HWADICG
    THIS%DWADICC=>DWADICC
    THIS%DWADICG=>DWADICG
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(CLNGLOTYPE),INTENT(INOUT) :: THIS
    NCLN=>THIS%NCLN
    ICLNCB=>THIS%ICLNCB
    ICLNHD=>THIS%ICLNHD
    ICLNDD=>THIS%ICLNDD
    ICLNIB=>THIS%ICLNIB
    NCLNNDS=>THIS%NCLNNDS
    NCLNGWC=>THIS%NCLNGWC
    NCONDUITYP=>THIS%NCONDUITYP
    NNDCLN=>THIS%NNDCLN
    IFLINCLN=>THIS%IFLINCLN
    ICCWADICLN=>THIS%ICCWADICLN
    ICGWADICLN=>THIS%ICGWADICLN
    CLNCON=>THIS%CLNCON
    ACLNNDS=>THIS%ACLNNDS
    ACLNGWC=>THIS%ACLNGWC
    ACLNCOND=>THIS%ACLNCOND
    HWADICC=>THIS%HWADICC
    HWADICG=>THIS%HWADICG
    DWADICC=>THIS%DWADICC
    DWADICG=>THIS%DWADICG
  END SUBROUTINE PNTSET
END MODULE CLN1MODULE
