MODULE GWFSTRMODULE
  IMPLICIT NONE
  INTEGER,SAVE,POINTER :: MXSTRM
  INTEGER,SAVE,POINTER :: NSTREM
  INTEGER,SAVE,POINTER :: NSS
  INTEGER,SAVE,POINTER :: NTRIB
  INTEGER,SAVE,POINTER :: NDIV
  INTEGER,SAVE,POINTER :: ICALC
  INTEGER,SAVE,POINTER :: ISTCB1
  INTEGER,SAVE,POINTER :: ISTCB2
  INTEGER,SAVE,POINTER :: IPTFLG
  INTEGER,SAVE,POINTER :: NSTRVL
  REAL,SAVE,POINTER :: CONST
  INTEGER,SAVE,POINTER :: NPSTR
  INTEGER,SAVE,POINTER :: ISTRPB
  REAL,SAVE,POINTER,DIMENSION(:,:) :: STRM
  REAL,SAVE,POINTER,DIMENSION(:) :: ARTRIB
  INTEGER,SAVE,POINTER,DIMENSION(:,:) :: ISTRM
  INTEGER,SAVE,POINTER,DIMENSION(:,:) :: ITRBAR
  INTEGER,SAVE,POINTER,DIMENSION(:) :: IDIVAR
  INTEGER,SAVE,POINTER,DIMENSION(:) :: NDFGAR
  CHARACTER(LEN=16),SAVE,DIMENSION(:),POINTER :: STRAUX
  TYPE :: GWFSTRTYPE
    INTEGER,POINTER :: MXSTRM
    INTEGER,POINTER :: NSTREM
    INTEGER,POINTER :: NSS
    INTEGER,POINTER :: NTRIB
    INTEGER,POINTER :: NDIV
    INTEGER,POINTER :: ICALC
    INTEGER,POINTER :: ISTCB1
    INTEGER,POINTER :: ISTCB2
    INTEGER,POINTER :: IPTFLG
    INTEGER,POINTER :: NSTRVL
    REAL,POINTER :: CONST
    INTEGER,POINTER :: NPSTR
    INTEGER,POINTER :: ISTRPB
    REAL,POINTER,DIMENSION(:,:) :: STRM
    REAL,POINTER,DIMENSION(:) :: ARTRIB
    INTEGER,POINTER,DIMENSION(:,:) :: ISTRM
    INTEGER,POINTER,DIMENSION(:,:) :: ITRBAR
    INTEGER,POINTER,DIMENSION(:) :: IDIVAR
    INTEGER,POINTER,DIMENSION(:) :: NDFGAR
    CHARACTER(LEN=16),DIMENSION(:),POINTER :: STRAUX
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE GWFSTRTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(GWFSTRTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%MXSTRM)
    DEALLOCATE(THIS%NSTREM)
    DEALLOCATE(THIS%NSS)
    DEALLOCATE(THIS%NTRIB)
    DEALLOCATE(THIS%NDIV)
    DEALLOCATE(THIS%ICALC)
    DEALLOCATE(THIS%ISTCB1)
    DEALLOCATE(THIS%ISTCB2)
    DEALLOCATE(THIS%IPTFLG)
    DEALLOCATE(THIS%NSTRVL)
    DEALLOCATE(THIS%CONST)
    DEALLOCATE(THIS%NPSTR)
    DEALLOCATE(THIS%ISTRPB)
    DEALLOCATE(THIS%STRM)
    DEALLOCATE(THIS%ARTRIB)
    DEALLOCATE(THIS%ISTRM)
    DEALLOCATE(THIS%ITRBAR)
    DEALLOCATE(THIS%IDIVAR)
    DEALLOCATE(THIS%NDFGAR)
    DEALLOCATE(THIS%STRAUX)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(GWFSTRTYPE),INTENT(INOUT) :: THIS
    THIS%MXSTRM=>MXSTRM
    THIS%NSTREM=>NSTREM
    THIS%NSS=>NSS
    THIS%NTRIB=>NTRIB
    THIS%NDIV=>NDIV
    THIS%ICALC=>ICALC
    THIS%ISTCB1=>ISTCB1
    THIS%ISTCB2=>ISTCB2
    THIS%IPTFLG=>IPTFLG
    THIS%NSTRVL=>NSTRVL
    THIS%CONST=>CONST
    THIS%NPSTR=>NPSTR
    THIS%ISTRPB=>ISTRPB
    THIS%STRM=>STRM
    THIS%ARTRIB=>ARTRIB
    THIS%ISTRM=>ISTRM
    THIS%ITRBAR=>ITRBAR
    THIS%IDIVAR=>IDIVAR
    THIS%NDFGAR=>NDFGAR
    THIS%STRAUX=>STRAUX
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(GWFSTRTYPE),INTENT(INOUT) :: THIS
    MXSTRM=>THIS%MXSTRM
    NSTREM=>THIS%NSTREM
    NSS=>THIS%NSS
    NTRIB=>THIS%NTRIB
    NDIV=>THIS%NDIV
    ICALC=>THIS%ICALC
    ISTCB1=>THIS%ISTCB1
    ISTCB2=>THIS%ISTCB2
    IPTFLG=>THIS%IPTFLG
    NSTRVL=>THIS%NSTRVL
    CONST=>THIS%CONST
    NPSTR=>THIS%NPSTR
    ISTRPB=>THIS%ISTRPB
    STRM=>THIS%STRM
    ARTRIB=>THIS%ARTRIB
    ISTRM=>THIS%ISTRM
    ITRBAR=>THIS%ITRBAR
    IDIVAR=>THIS%IDIVAR
    NDFGAR=>THIS%NDFGAR
    STRAUX=>THIS%STRAUX
  END SUBROUTINE PNTSET
END MODULE GWFSTRMODULE
