MODULE GLOBAL
  IMPLICIT NONE
  INTEGER,PARAMETER :: NIUNIT=100
  INTEGER,SAVE,POINTER :: IUNSAT
  INTEGER,SAVE,POINTER :: NCOL
  INTEGER,SAVE,POINTER :: NROW
  INTEGER,SAVE,POINTER :: NLAY
  INTEGER,SAVE,POINTER :: NPER
  INTEGER,SAVE,POINTER :: NBOTM
  INTEGER,SAVE,POINTER :: NCNFBD
  INTEGER,SAVE,POINTER :: IVSD
  INTEGER,SAVE,POINTER :: ITMUNI
  INTEGER,SAVE,POINTER :: LENUNI
  INTEGER,SAVE,POINTER :: IXSEC
  INTEGER,SAVE,POINTER :: ITRSS
  INTEGER,SAVE,POINTER :: INBAS
  INTEGER,SAVE,POINTER :: IUNSTR
  INTEGER,SAVE,POINTER :: IDEALLOC_LPF
  INTEGER,SAVE,POINTER :: IDEALLOC_HY
  INTEGER,SAVE,POINTER :: ISYMFLG
  INTEGER,SAVE,POINTER :: ITRNSP
  INTEGER,SAVE,POINTER :: NEQS
  INTEGER,SAVE,POINTER :: NODES
  INTEGER,SAVE,POINTER :: NJA
  INTEGER,SAVE,POINTER :: NJAS
  INTEGER,SAVE,POINTER :: NJAG
  INTEGER,SAVE,POINTER :: IOUT
  INTEGER,SAVE,POINTER :: IPRCONN
  INTEGER,SAVE,POINTER :: IDSYMRD
  INTEGER,SAVE,POINTER :: ILAYCON4
  INTEGER,SAVE,POINTER :: IWADI
  INTEGER,SAVE,POINTER :: IWADICLN
  INTEGER,SAVE,POINTER :: INCLN
  INTEGER,SAVE,POINTER :: INGNC
  INTEGER,SAVE,POINTER :: INGNC2
  INTEGER,SAVE,POINTER :: INGNCN
  INTEGER,SAVE,POINTER :: IFREFM
  INTEGER,SAVE,POINTER :: MXNODLAY
  INTEGER,SAVE,POINTER :: NOCVCO
  INTEGER,SAVE,POINTER :: ICONCV
  INTEGER,SAVE,POINTER :: NOVFC
  DOUBLE PRECISION,SAVE,POINTER :: WADIEPS
  INTEGER,SAVE,DIMENSION(:),POINTER :: IUNIT
  INTEGER,SAVE,DIMENSION(:),POINTER :: IBOUND
  INTEGER,SAVE,DIMENSION(:),POINTER :: IA
  INTEGER,SAVE,DIMENSION(:),POINTER :: IAG
  REAL,DIMENSION(:),POINTER :: FLOWJA
  INTEGER,POINTER,DIMENSION(:) :: IATMP
  INTEGER,POINTER :: NJATMP
  INTEGER,SAVE,DIMENSION(:),POINTER :: JA
  INTEGER,SAVE,DIMENSION(:),POINTER :: JAFL
  INTEGER,SAVE,DIMENSION(:),POINTER :: JAS
  INTEGER,SAVE,DIMENSION(:),POINTER :: ISYM
  INTEGER,SAVE,DIMENSION(:),POINTER :: IVC
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: HOLD
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: HNEW
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: RHS
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: AMAT
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: SN
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: SO
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: AKRC
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: AKR
  REAL,DIMENSION(:),POINTER :: DELR
  REAL,DIMENSION(:),POINTER :: DELC
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: BOT
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: TOP
  DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: PGF
  REAL,SAVE,DIMENSION(:),POINTER :: AREA
  REAL,SAVE,DIMENSION(:),POINTER :: FAHL
  REAL,SAVE,DIMENSION(:),POINTER :: CL1
  REAL,SAVE,DIMENSION(:),POINTER :: CL2
  REAL,SAVE,DIMENSION(:),POINTER :: ARAD
  INTEGER,SAVE,DIMENSION(:),POINTER :: NODLAY
  INTEGER,DIMENSION(:),POINTER :: LAYCBD
  INTEGER,SAVE,DIMENSION(:),POINTER :: LAYHDT
  INTEGER,SAVE,DIMENSION(:),POINTER :: LAYHDS
  REAL,SAVE,DIMENSION(:),POINTER :: PERLEN
  INTEGER,SAVE,DIMENSION(:),POINTER :: NSTP
  REAL,SAVE,DIMENSION(:),POINTER :: TSMULT
  INTEGER,SAVE,DIMENSION(:),POINTER :: ISSFLG
  REAL,SAVE,DIMENSION(:),POINTER :: BUFF
  REAL,SAVE,DIMENSION(:),POINTER :: STRT
  DOUBLE PRECISION,SAVE,POINTER,DIMENSION(:) :: HWADI
  DOUBLE PRECISION,SAVE,POINTER,DIMENSION(:) :: DWADI
  TYPE :: GWFGLOTYPE
    INTEGER,POINTER :: IUNSAT
    INTEGER,POINTER :: NCOL
    INTEGER,POINTER :: NROW
    INTEGER,POINTER :: NLAY
    INTEGER,POINTER :: NPER
    INTEGER,POINTER :: NBOTM
    INTEGER,POINTER :: NCNFBD
    INTEGER,POINTER :: IVSD
    INTEGER,POINTER :: ITMUNI
    INTEGER,POINTER :: LENUNI
    INTEGER,POINTER :: IXSEC
    INTEGER,POINTER :: ITRSS
    INTEGER,POINTER :: INBAS
    INTEGER,POINTER :: IUNSTR
    INTEGER,POINTER :: IDEALLOC_LPF
    INTEGER,POINTER :: IDEALLOC_HY
    INTEGER,POINTER :: ISYMFLG
    INTEGER,POINTER :: ITRNSP
    INTEGER,POINTER :: NEQS
    INTEGER,POINTER :: NODES
    INTEGER,POINTER :: NJA
    INTEGER,POINTER :: NJAS
    INTEGER,POINTER :: NJAG
    INTEGER,POINTER :: IOUT
    INTEGER,POINTER :: IPRCONN
    INTEGER,POINTER :: IDSYMRD
    INTEGER,POINTER :: ILAYCON4
    INTEGER,POINTER :: IWADI
    INTEGER,POINTER :: IWADICLN
    INTEGER,POINTER :: INCLN
    INTEGER,POINTER :: INGNC
    INTEGER,POINTER :: INGNC2
    INTEGER,POINTER :: INGNCN
    INTEGER,POINTER :: IFREFM
    INTEGER,POINTER :: MXNODLAY
    INTEGER,POINTER :: NOCVCO
    INTEGER,POINTER :: ICONCV
    INTEGER,POINTER :: NOVFC
    DOUBLE PRECISION,POINTER :: WADIEPS
    INTEGER,DIMENSION(:),POINTER :: IUNIT
    INTEGER,DIMENSION(:),POINTER :: IBOUND
    INTEGER,DIMENSION(:),POINTER :: IA
    INTEGER,DIMENSION(:),POINTER :: IAG
    REAL,DIMENSION(:),POINTER :: FLOWJA
    INTEGER,POINTER,DIMENSION(:) :: IATMP
    INTEGER,POINTER :: NJATMP
    INTEGER,DIMENSION(:),POINTER :: JA
    INTEGER,DIMENSION(:),POINTER :: JAFL
    INTEGER,DIMENSION(:),POINTER :: JAS
    INTEGER,DIMENSION(:),POINTER :: ISYM
    INTEGER,DIMENSION(:),POINTER :: IVC
    DOUBLE PRECISION,DIMENSION(:),POINTER :: HOLD
    DOUBLE PRECISION,DIMENSION(:),POINTER :: HNEW
    DOUBLE PRECISION,DIMENSION(:),POINTER :: RHS
    DOUBLE PRECISION,DIMENSION(:),POINTER :: AMAT
    DOUBLE PRECISION,DIMENSION(:),POINTER :: SN
    DOUBLE PRECISION,DIMENSION(:),POINTER :: SO
    DOUBLE PRECISION,DIMENSION(:),POINTER :: AKRC
    DOUBLE PRECISION,DIMENSION(:),POINTER :: AKR
    REAL,DIMENSION(:),POINTER :: DELR
    REAL,DIMENSION(:),POINTER :: DELC
    DOUBLE PRECISION,DIMENSION(:),POINTER :: BOT
    DOUBLE PRECISION,DIMENSION(:),POINTER :: TOP
    DOUBLE PRECISION,DIMENSION(:),POINTER :: PGF
    REAL,DIMENSION(:),POINTER :: AREA
    REAL,DIMENSION(:),POINTER :: FAHL
    REAL,DIMENSION(:),POINTER :: CL1
    REAL,DIMENSION(:),POINTER :: CL2
    REAL,DIMENSION(:),POINTER :: ARAD
    INTEGER,DIMENSION(:),POINTER :: NODLAY
    INTEGER,DIMENSION(:),POINTER :: LAYCBD
    INTEGER,DIMENSION(:),POINTER :: LAYHDT
    INTEGER,DIMENSION(:),POINTER :: LAYHDS
    REAL,DIMENSION(:),POINTER :: PERLEN
    INTEGER,DIMENSION(:),POINTER :: NSTP
    REAL,DIMENSION(:),POINTER :: TSMULT
    INTEGER,DIMENSION(:),POINTER :: ISSFLG
    REAL,DIMENSION(:),POINTER :: BUFF
    REAL,DIMENSION(:),POINTER :: STRT
    DOUBLE PRECISION,POINTER,DIMENSION(:) :: HWADI
    DOUBLE PRECISION,POINTER,DIMENSION(:) :: DWADI
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE GWFGLOTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(GWFGLOTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%IUNSAT)
    DEALLOCATE(THIS%NCOL)
    DEALLOCATE(THIS%NROW)
    DEALLOCATE(THIS%NLAY)
    DEALLOCATE(THIS%NPER)
    DEALLOCATE(THIS%NBOTM)
    DEALLOCATE(THIS%NCNFBD)
    DEALLOCATE(THIS%IVSD)
    DEALLOCATE(THIS%ITMUNI)
    DEALLOCATE(THIS%LENUNI)
    DEALLOCATE(THIS%IXSEC)
    DEALLOCATE(THIS%ITRSS)
    DEALLOCATE(THIS%INBAS)
    DEALLOCATE(THIS%IUNSTR)
    DEALLOCATE(THIS%IDEALLOC_LPF)
    DEALLOCATE(THIS%IDEALLOC_HY)
    DEALLOCATE(THIS%ISYMFLG)
    DEALLOCATE(THIS%ITRNSP)
    DEALLOCATE(THIS%NEQS)
    DEALLOCATE(THIS%NODES)
    DEALLOCATE(THIS%NJA)
    DEALLOCATE(THIS%NJAS)
    DEALLOCATE(THIS%NJAG)
    DEALLOCATE(THIS%IOUT)
    DEALLOCATE(THIS%IPRCONN)
    DEALLOCATE(THIS%IDSYMRD)
    DEALLOCATE(THIS%ILAYCON4)
    DEALLOCATE(THIS%IWADI)
    DEALLOCATE(THIS%IWADICLN)
    DEALLOCATE(THIS%INCLN)
    DEALLOCATE(THIS%INGNC)
    DEALLOCATE(THIS%INGNC2)
    DEALLOCATE(THIS%INGNCN)
    DEALLOCATE(THIS%IFREFM)
    DEALLOCATE(THIS%MXNODLAY)
    DEALLOCATE(THIS%NOCVCO)
    DEALLOCATE(THIS%ICONCV)
    DEALLOCATE(THIS%NOVFC)
    DEALLOCATE(THIS%WADIEPS)
    DEALLOCATE(THIS%IUNIT)
    DEALLOCATE(THIS%IBOUND)
    DEALLOCATE(THIS%IA)
    DEALLOCATE(THIS%IAG)
    DEALLOCATE(THIS%FLOWJA)
    DEALLOCATE(THIS%IATMP)
    DEALLOCATE(THIS%NJATMP)
    DEALLOCATE(THIS%JA)
    DEALLOCATE(THIS%JAFL)
    DEALLOCATE(THIS%JAS)
    DEALLOCATE(THIS%ISYM)
    DEALLOCATE(THIS%IVC)
    DEALLOCATE(THIS%HOLD)
    DEALLOCATE(THIS%HNEW)
    DEALLOCATE(THIS%RHS)
    DEALLOCATE(THIS%AMAT)
    DEALLOCATE(THIS%SN)
    DEALLOCATE(THIS%SO)
    DEALLOCATE(THIS%AKRC)
    DEALLOCATE(THIS%AKR)
    DEALLOCATE(THIS%DELR)
    DEALLOCATE(THIS%DELC)
    DEALLOCATE(THIS%BOT)
    DEALLOCATE(THIS%TOP)
    DEALLOCATE(THIS%PGF)
    DEALLOCATE(THIS%AREA)
    DEALLOCATE(THIS%FAHL)
    DEALLOCATE(THIS%CL1)
    DEALLOCATE(THIS%CL2)
    DEALLOCATE(THIS%ARAD)
    DEALLOCATE(THIS%NODLAY)
    DEALLOCATE(THIS%LAYCBD)
    DEALLOCATE(THIS%LAYHDT)
    DEALLOCATE(THIS%LAYHDS)
    DEALLOCATE(THIS%PERLEN)
    DEALLOCATE(THIS%NSTP)
    DEALLOCATE(THIS%TSMULT)
    DEALLOCATE(THIS%ISSFLG)
    DEALLOCATE(THIS%BUFF)
    DEALLOCATE(THIS%STRT)
    DEALLOCATE(THIS%HWADI)
    DEALLOCATE(THIS%DWADI)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(GWFGLOTYPE),INTENT(INOUT) :: THIS
    THIS%IUNSAT=>IUNSAT
    THIS%NCOL=>NCOL
    THIS%NROW=>NROW
    THIS%NLAY=>NLAY
    THIS%NPER=>NPER
    THIS%NBOTM=>NBOTM
    THIS%NCNFBD=>NCNFBD
    THIS%IVSD=>IVSD
    THIS%ITMUNI=>ITMUNI
    THIS%LENUNI=>LENUNI
    THIS%IXSEC=>IXSEC
    THIS%ITRSS=>ITRSS
    THIS%INBAS=>INBAS
    THIS%IUNSTR=>IUNSTR
    THIS%IDEALLOC_LPF=>IDEALLOC_LPF
    THIS%IDEALLOC_HY=>IDEALLOC_HY
    THIS%ISYMFLG=>ISYMFLG
    THIS%ITRNSP=>ITRNSP
    THIS%NEQS=>NEQS
    THIS%NODES=>NODES
    THIS%NJA=>NJA
    THIS%NJAS=>NJAS
    THIS%NJAG=>NJAG
    THIS%IOUT=>IOUT
    THIS%IPRCONN=>IPRCONN
    THIS%IDSYMRD=>IDSYMRD
    THIS%ILAYCON4=>ILAYCON4
    THIS%IWADI=>IWADI
    THIS%IWADICLN=>IWADICLN
    THIS%INCLN=>INCLN
    THIS%INGNC=>INGNC
    THIS%INGNC2=>INGNC2
    THIS%INGNCN=>INGNCN
    THIS%IFREFM=>IFREFM
    THIS%MXNODLAY=>MXNODLAY
    THIS%NOCVCO=>NOCVCO
    THIS%ICONCV=>ICONCV
    THIS%NOVFC=>NOVFC
    THIS%WADIEPS=>WADIEPS
    THIS%IUNIT=>IUNIT
    THIS%IBOUND=>IBOUND
    THIS%IA=>IA
    THIS%IAG=>IAG
    THIS%FLOWJA=>FLOWJA
    THIS%IATMP=>IATMP
    THIS%NJATMP=>NJATMP
    THIS%JA=>JA
    THIS%JAFL=>JAFL
    THIS%JAS=>JAS
    THIS%ISYM=>ISYM
    THIS%IVC=>IVC
    THIS%HOLD=>HOLD
    THIS%HNEW=>HNEW
    THIS%RHS=>RHS
    THIS%AMAT=>AMAT
    THIS%SN=>SN
    THIS%SO=>SO
    THIS%AKRC=>AKRC
    THIS%AKR=>AKR
    THIS%DELR=>DELR
    THIS%DELC=>DELC
    THIS%BOT=>BOT
    THIS%TOP=>TOP
    THIS%PGF=>PGF
    THIS%AREA=>AREA
    THIS%FAHL=>FAHL
    THIS%CL1=>CL1
    THIS%CL2=>CL2
    THIS%ARAD=>ARAD
    THIS%NODLAY=>NODLAY
    THIS%LAYCBD=>LAYCBD
    THIS%LAYHDT=>LAYHDT
    THIS%LAYHDS=>LAYHDS
    THIS%PERLEN=>PERLEN
    THIS%NSTP=>NSTP
    THIS%TSMULT=>TSMULT
    THIS%ISSFLG=>ISSFLG
    THIS%BUFF=>BUFF
    THIS%STRT=>STRT
    THIS%HWADI=>HWADI
    THIS%DWADI=>DWADI
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(GWFGLOTYPE),INTENT(INOUT) :: THIS
    IUNSAT=>THIS%IUNSAT
    NCOL=>THIS%NCOL
    NROW=>THIS%NROW
    NLAY=>THIS%NLAY
    NPER=>THIS%NPER
    NBOTM=>THIS%NBOTM
    NCNFBD=>THIS%NCNFBD
    IVSD=>THIS%IVSD
    ITMUNI=>THIS%ITMUNI
    LENUNI=>THIS%LENUNI
    IXSEC=>THIS%IXSEC
    ITRSS=>THIS%ITRSS
    INBAS=>THIS%INBAS
    IUNSTR=>THIS%IUNSTR
    IDEALLOC_LPF=>THIS%IDEALLOC_LPF
    IDEALLOC_HY=>THIS%IDEALLOC_HY
    ISYMFLG=>THIS%ISYMFLG
    ITRNSP=>THIS%ITRNSP
    NEQS=>THIS%NEQS
    NODES=>THIS%NODES
    NJA=>THIS%NJA
    NJAS=>THIS%NJAS
    NJAG=>THIS%NJAG
    IOUT=>THIS%IOUT
    IPRCONN=>THIS%IPRCONN
    IDSYMRD=>THIS%IDSYMRD
    ILAYCON4=>THIS%ILAYCON4
    IWADI=>THIS%IWADI
    IWADICLN=>THIS%IWADICLN
    INCLN=>THIS%INCLN
    INGNC=>THIS%INGNC
    INGNC2=>THIS%INGNC2
    INGNCN=>THIS%INGNCN
    IFREFM=>THIS%IFREFM
    MXNODLAY=>THIS%MXNODLAY
    NOCVCO=>THIS%NOCVCO
    ICONCV=>THIS%ICONCV
    NOVFC=>THIS%NOVFC
    WADIEPS=>THIS%WADIEPS
    IUNIT=>THIS%IUNIT
    IBOUND=>THIS%IBOUND
    IA=>THIS%IA
    IAG=>THIS%IAG
    FLOWJA=>THIS%FLOWJA
    IATMP=>THIS%IATMP
    NJATMP=>THIS%NJATMP
    JA=>THIS%JA
    JAFL=>THIS%JAFL
    JAS=>THIS%JAS
    ISYM=>THIS%ISYM
    IVC=>THIS%IVC
    HOLD=>THIS%HOLD
    HNEW=>THIS%HNEW
    RHS=>THIS%RHS
    AMAT=>THIS%AMAT
    SN=>THIS%SN
    SO=>THIS%SO
    AKRC=>THIS%AKRC
    AKR=>THIS%AKR
    DELR=>THIS%DELR
    DELC=>THIS%DELC
    BOT=>THIS%BOT
    TOP=>THIS%TOP
    PGF=>THIS%PGF
    AREA=>THIS%AREA
    FAHL=>THIS%FAHL
    CL1=>THIS%CL1
    CL2=>THIS%CL2
    ARAD=>THIS%ARAD
    NODLAY=>THIS%NODLAY
    LAYCBD=>THIS%LAYCBD
    LAYHDT=>THIS%LAYHDT
    LAYHDS=>THIS%LAYHDS
    PERLEN=>THIS%PERLEN
    NSTP=>THIS%NSTP
    TSMULT=>THIS%TSMULT
    ISSFLG=>THIS%ISSFLG
    BUFF=>THIS%BUFF
    STRT=>THIS%STRT
    HWADI=>THIS%HWADI
    DWADI=>THIS%DWADI
  END SUBROUTINE PNTSET
END MODULE GLOBAL
