MODULE PARAMMODULE
  IMPLICIT NONE
  INTEGER,PARAMETER :: MXPAR=999
  INTEGER,PARAMETER :: MXCLST=1000
  INTEGER,PARAMETER :: MXINST=1000
  INTEGER,SAVE,POINTER :: ICLSUM
  INTEGER,SAVE,POINTER :: IPSUM
  INTEGER,SAVE,POINTER :: INAMLOC
  INTEGER,SAVE,POINTER :: NMLTAR
  INTEGER,SAVE,POINTER :: NZONAR
  INTEGER,SAVE,POINTER :: NPVAL
  REAL,SAVE,DIMENSION(:),POINTER :: B
  INTEGER,SAVE,DIMENSION(:),POINTER :: IACTIVE
  INTEGER,SAVE,DIMENSION(:,:),POINTER :: IPLOC
  INTEGER,SAVE,DIMENSION(:,:),POINTER :: IPCLST
  INTEGER,SAVE,DIMENSION(:,:,:),POINTER :: IZON
  REAL,SAVE,DIMENSION(:,:,:),POINTER :: RMLT
  CHARACTER(LEN=10),SAVE,DIMENSION(:),POINTER :: PARNAM
  CHARACTER(LEN=4),SAVE,DIMENSION(:),POINTER :: PARTYP
  CHARACTER(LEN=10),SAVE,DIMENSION(:),POINTER :: ZONNAM
  CHARACTER(LEN=10),SAVE,DIMENSION(:),POINTER :: MLTNAM
  CHARACTER(LEN=10),SAVE,DIMENSION(:),POINTER :: INAME
  TYPE :: GWFPARAMTYPE
    INTEGER,POINTER :: ICLSUM
    INTEGER,POINTER :: IPSUM
    INTEGER,POINTER :: INAMLOC
    INTEGER,POINTER :: NMLTAR
    INTEGER,POINTER :: NZONAR
    INTEGER,POINTER :: NPVAL
    REAL,DIMENSION(:),POINTER :: B
    INTEGER,DIMENSION(:),POINTER :: IACTIVE
    INTEGER,DIMENSION(:,:),POINTER :: IPLOC
    INTEGER,DIMENSION(:,:),POINTER :: IPCLST
    INTEGER,DIMENSION(:,:,:),POINTER :: IZON
    REAL,DIMENSION(:,:,:),POINTER :: RMLT
    CHARACTER(LEN=10),DIMENSION(:),POINTER :: PARNAM
    CHARACTER(LEN=4),DIMENSION(:),POINTER :: PARTYP
    CHARACTER(LEN=10),DIMENSION(:),POINTER :: ZONNAM
    CHARACTER(LEN=10),DIMENSION(:),POINTER :: MLTNAM
    CHARACTER(LEN=10),DIMENSION(:),POINTER :: INAME
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE GWFPARAMTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(GWFPARAMTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%ICLSUM)
    DEALLOCATE(THIS%IPSUM)
    DEALLOCATE(THIS%INAMLOC)
    DEALLOCATE(THIS%NMLTAR)
    DEALLOCATE(THIS%NZONAR)
    DEALLOCATE(THIS%NPVAL)
    DEALLOCATE(THIS%B)
    DEALLOCATE(THIS%IACTIVE)
    DEALLOCATE(THIS%IPLOC)
    DEALLOCATE(THIS%IPCLST)
    DEALLOCATE(THIS%IZON)
    DEALLOCATE(THIS%RMLT)
    DEALLOCATE(THIS%PARNAM)
    DEALLOCATE(THIS%PARTYP)
    DEALLOCATE(THIS%ZONNAM)
    DEALLOCATE(THIS%MLTNAM)
    DEALLOCATE(THIS%INAME)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(GWFPARAMTYPE),INTENT(INOUT) :: THIS
    THIS%ICLSUM=>ICLSUM
    THIS%IPSUM=>IPSUM
    THIS%INAMLOC=>INAMLOC
    THIS%NMLTAR=>NMLTAR
    THIS%NZONAR=>NZONAR
    THIS%NPVAL=>NPVAL
    THIS%B=>B
    THIS%IACTIVE=>IACTIVE
    THIS%IPLOC=>IPLOC
    THIS%IPCLST=>IPCLST
    THIS%IZON=>IZON
    THIS%RMLT=>RMLT
    THIS%PARNAM=>PARNAM
    THIS%PARTYP=>PARTYP
    THIS%ZONNAM=>ZONNAM
    THIS%MLTNAM=>MLTNAM
    THIS%INAME=>INAME
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(GWFPARAMTYPE),INTENT(INOUT) :: THIS
    ICLSUM=>THIS%ICLSUM
    IPSUM=>THIS%IPSUM
    INAMLOC=>THIS%INAMLOC
    NMLTAR=>THIS%NMLTAR
    NZONAR=>THIS%NZONAR
    NPVAL=>THIS%NPVAL
    B=>THIS%B
    IACTIVE=>THIS%IACTIVE
    IPLOC=>THIS%IPLOC
    IPCLST=>THIS%IPCLST
    IZON=>THIS%IZON
    RMLT=>THIS%RMLT
    PARNAM=>THIS%PARNAM
    PARTYP=>THIS%PARTYP
    ZONNAM=>THIS%ZONNAM
    MLTNAM=>THIS%MLTNAM
    INAME=>THIS%INAME
  END SUBROUTINE PNTSET
END MODULE PARAMMODULE
