MODULE GWFRIVMODULE
  IMPLICIT NONE
  INTEGER,SAVE,POINTER :: NRIVER
  INTEGER,SAVE,POINTER :: MXRIVR
  INTEGER,SAVE,POINTER :: NRIVVL
  INTEGER,SAVE,POINTER :: IRIVCB
  INTEGER,SAVE,POINTER :: IPRRIV
  INTEGER,SAVE,POINTER :: NPRIV
  INTEGER,SAVE,POINTER :: IRIVPB
  INTEGER,SAVE,POINTER :: NNPRIV
  CHARACTER(LEN=16),SAVE,DIMENSION(:),POINTER :: RIVAUX
  REAL,SAVE,DIMENSION(:,:),POINTER :: RIVR
  TYPE :: GWFRIVTYPE
    INTEGER,POINTER :: NRIVER
    INTEGER,POINTER :: MXRIVR
    INTEGER,POINTER :: NRIVVL
    INTEGER,POINTER :: IRIVCB
    INTEGER,POINTER :: IPRRIV
    INTEGER,POINTER :: NPRIV
    INTEGER,POINTER :: IRIVPB
    INTEGER,POINTER :: NNPRIV
    CHARACTER(LEN=16),DIMENSION(:),POINTER :: RIVAUX
    REAL,DIMENSION(:,:),POINTER :: RIVR
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE GWFRIVTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(GWFRIVTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%NRIVER)
    DEALLOCATE(THIS%MXRIVR)
    DEALLOCATE(THIS%NRIVVL)
    DEALLOCATE(THIS%IRIVCB)
    DEALLOCATE(THIS%IPRRIV)
    DEALLOCATE(THIS%NPRIV)
    DEALLOCATE(THIS%IRIVPB)
    DEALLOCATE(THIS%NNPRIV)
    DEALLOCATE(THIS%RIVAUX)
    DEALLOCATE(THIS%RIVR)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(GWFRIVTYPE),INTENT(INOUT) :: THIS
    THIS%NRIVER=>NRIVER
    THIS%MXRIVR=>MXRIVR
    THIS%NRIVVL=>NRIVVL
    THIS%IRIVCB=>IRIVCB
    THIS%IPRRIV=>IPRRIV
    THIS%NPRIV=>NPRIV
    THIS%IRIVPB=>IRIVPB
    THIS%NNPRIV=>NNPRIV
    THIS%RIVAUX=>RIVAUX
    THIS%RIVR=>RIVR
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(GWFRIVTYPE),INTENT(INOUT) :: THIS
    NRIVER=>THIS%NRIVER
    MXRIVR=>THIS%MXRIVR
    NRIVVL=>THIS%NRIVVL
    IRIVCB=>THIS%IRIVCB
    IPRRIV=>THIS%IPRRIV
    NPRIV=>THIS%NPRIV
    IRIVPB=>THIS%IRIVPB
    NNPRIV=>THIS%NNPRIV
    RIVAUX=>THIS%RIVAUX
    RIVR=>THIS%RIVR
  END SUBROUTINE PNTSET
END MODULE GWFRIVMODULE
