MODULE GWFHFBMODULE
  IMPLICIT NONE
  INTEGER,POINTER :: MXHFB
  INTEGER,POINTER :: NHFB
  INTEGER,POINTER :: IPRHFB
  INTEGER,POINTER :: NHFBNP
  INTEGER,POINTER :: NPHFB
  INTEGER,POINTER :: IHFBPB
  REAL,DIMENSION(:,:),POINTER :: HFB
  TYPE :: GWFHFBTYPE
    INTEGER,POINTER :: MXHFB
    INTEGER,POINTER :: NHFB
    INTEGER,POINTER :: IPRHFB
    INTEGER,POINTER :: NHFBNP
    INTEGER,POINTER :: NPHFB
    INTEGER,POINTER :: IHFBPB
    REAL,DIMENSION(:,:),POINTER :: HFB
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE GWFHFBTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(GWFHFBTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%MXHFB)
    DEALLOCATE(THIS%NHFB)
    DEALLOCATE(THIS%IPRHFB)
    DEALLOCATE(THIS%NHFBNP)
    DEALLOCATE(THIS%NPHFB)
    DEALLOCATE(THIS%IHFBPB)
    DEALLOCATE(THIS%HFB)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(GWFHFBTYPE),INTENT(INOUT) :: THIS
    THIS%MXHFB=>MXHFB
    THIS%NHFB=>NHFB
    THIS%IPRHFB=>IPRHFB
    THIS%NHFBNP=>NHFBNP
    THIS%NPHFB=>NPHFB
    THIS%IHFBPB=>IHFBPB
    THIS%HFB=>HFB
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(GWFHFBTYPE),INTENT(INOUT) :: THIS
    MXHFB=>THIS%MXHFB
    NHFB=>THIS%NHFB
    IPRHFB=>THIS%IPRHFB
    NHFBNP=>THIS%NHFBNP
    NPHFB=>THIS%NPHFB
    IHFBPB=>THIS%IHFBPB
    HFB=>THIS%HFB
  END SUBROUTINE PNTSET
END MODULE GWFHFBMODULE
