MODULE GWFEVTMODULE
  IMPLICIT NONE
  INTEGER,SAVE,POINTER :: NEVTOP
  INTEGER,SAVE,POINTER :: IEVTCB
  INTEGER,SAVE,POINTER :: MXNDEVT
  INTEGER,SAVE,POINTER :: INIEVT
  INTEGER,SAVE,POINTER :: NIEVT
  INTEGER,SAVE,POINTER :: MXZNEVT
  INTEGER,SAVE,POINTER :: NPEVT
  INTEGER,SAVE,POINTER :: IEVTPF
  REAL,SAVE,DIMENSION(:),POINTER :: EVTR
  REAL,SAVE,DIMENSION(:),POINTER :: EXDP
  REAL,SAVE,DIMENSION(:),POINTER :: SURF
  REAL,SAVE,DIMENSION(:),POINTER :: EVTF
  REAL,SAVE,DIMENSION(:),POINTER :: ETFACTOR
  INTEGER,SAVE,DIMENSION(:),POINTER :: IEVT
  INTEGER,SAVE,DIMENSION(:),POINTER :: IZNEVT
  TYPE :: GWFEVTTYPE
    INTEGER,POINTER :: NEVTOP
    INTEGER,POINTER :: IEVTCB
    INTEGER,POINTER :: MXNDEVT
    INTEGER,POINTER :: INIEVT
    INTEGER,POINTER :: NIEVT
    INTEGER,POINTER :: MXZNEVT
    INTEGER,POINTER :: NPEVT
    INTEGER,POINTER :: IEVTPF
    REAL,DIMENSION(:),POINTER :: EVTR
    REAL,DIMENSION(:),POINTER :: EXDP
    REAL,DIMENSION(:),POINTER :: SURF
    REAL,DIMENSION(:),POINTER :: EVTF
    REAL,DIMENSION(:),POINTER :: ETFACTOR
    INTEGER,DIMENSION(:),POINTER :: IEVT
    INTEGER,DIMENSION(:),POINTER :: IZNEVT
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE GWFEVTTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(GWFEVTTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%NEVTOP)
    DEALLOCATE(THIS%IEVTCB)
    DEALLOCATE(THIS%MXNDEVT)
    DEALLOCATE(THIS%INIEVT)
    DEALLOCATE(THIS%NIEVT)
    DEALLOCATE(THIS%MXZNEVT)
    DEALLOCATE(THIS%NPEVT)
    DEALLOCATE(THIS%IEVTPF)
    DEALLOCATE(THIS%EVTR)
    DEALLOCATE(THIS%EXDP)
    DEALLOCATE(THIS%SURF)
    DEALLOCATE(THIS%EVTF)
    DEALLOCATE(THIS%ETFACTOR)
    DEALLOCATE(THIS%IEVT)
    DEALLOCATE(THIS%IZNEVT)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(GWFEVTTYPE),INTENT(INOUT) :: THIS
    THIS%NEVTOP=>NEVTOP
    THIS%IEVTCB=>IEVTCB
    THIS%MXNDEVT=>MXNDEVT
    THIS%INIEVT=>INIEVT
    THIS%NIEVT=>NIEVT
    THIS%MXZNEVT=>MXZNEVT
    THIS%NPEVT=>NPEVT
    THIS%IEVTPF=>IEVTPF
    THIS%EVTR=>EVTR
    THIS%EXDP=>EXDP
    THIS%SURF=>SURF
    THIS%EVTF=>EVTF
    THIS%ETFACTOR=>ETFACTOR
    THIS%IEVT=>IEVT
    THIS%IZNEVT=>IZNEVT
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(GWFEVTTYPE),INTENT(INOUT) :: THIS
    NEVTOP=>THIS%NEVTOP
    IEVTCB=>THIS%IEVTCB
    MXNDEVT=>THIS%MXNDEVT
    INIEVT=>THIS%INIEVT
    NIEVT=>THIS%NIEVT
    MXZNEVT=>THIS%MXZNEVT
    NPEVT=>THIS%NPEVT
    IEVTPF=>THIS%IEVTPF
    EVTR=>THIS%EVTR
    EXDP=>THIS%EXDP
    SURF=>THIS%SURF
    EVTF=>THIS%EVTF
    ETFACTOR=>THIS%ETFACTOR
    IEVT=>THIS%IEVT
    IZNEVT=>THIS%IZNEVT
  END SUBROUTINE PNTSET
END MODULE GWFEVTMODULE
