MODULE GWFDRNMODULE
  IMPLICIT NONE
  INTEGER,SAVE,POINTER :: NDRAIN
  INTEGER,SAVE,POINTER :: MXDRN
  INTEGER,SAVE,POINTER :: NDRNVL
  INTEGER,SAVE,POINTER :: IDRNCB
  INTEGER,SAVE,POINTER :: IPRDRN
  INTEGER,SAVE,POINTER :: NPDRN
  INTEGER,SAVE,POINTER :: IDRNPB
  INTEGER,SAVE,POINTER :: NNPDRN
  CHARACTER(LEN=16),SAVE,DIMENSION(:),POINTER :: DRNAUX
  REAL,SAVE,DIMENSION(:,:),POINTER :: DRAI
  TYPE :: GWFDRNTYPE
    INTEGER,POINTER :: NDRAIN
    INTEGER,POINTER :: MXDRN
    INTEGER,POINTER :: NDRNVL
    INTEGER,POINTER :: IDRNCB
    INTEGER,POINTER :: IPRDRN
    INTEGER,POINTER :: NPDRN
    INTEGER,POINTER :: IDRNPB
    INTEGER,POINTER :: NNPDRN
    CHARACTER(LEN=16),DIMENSION(:),POINTER :: DRNAUX
    REAL,DIMENSION(:,:),POINTER :: DRAI
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE GWFDRNTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(GWFDRNTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%NDRAIN)
    DEALLOCATE(THIS%MXDRN)
    DEALLOCATE(THIS%NDRNVL)
    DEALLOCATE(THIS%IDRNCB)
    DEALLOCATE(THIS%IPRDRN)
    DEALLOCATE(THIS%NPDRN)
    DEALLOCATE(THIS%IDRNPB)
    DEALLOCATE(THIS%NNPDRN)
    DEALLOCATE(THIS%DRNAUX)
    DEALLOCATE(THIS%DRAI)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(GWFDRNTYPE),INTENT(INOUT) :: THIS
    THIS%NDRAIN=>NDRAIN
    THIS%MXDRN=>MXDRN
    THIS%NDRNVL=>NDRNVL
    THIS%IDRNCB=>IDRNCB
    THIS%IPRDRN=>IPRDRN
    THIS%NPDRN=>NPDRN
    THIS%IDRNPB=>IDRNPB
    THIS%NNPDRN=>NNPDRN
    THIS%DRNAUX=>DRNAUX
    THIS%DRAI=>DRAI
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(GWFDRNTYPE),INTENT(INOUT) :: THIS
    NDRAIN=>THIS%NDRAIN
    MXDRN=>THIS%MXDRN
    NDRNVL=>THIS%NDRNVL
    IDRNCB=>THIS%IDRNCB
    IPRDRN=>THIS%IPRDRN
    NPDRN=>THIS%NPDRN
    IDRNPB=>THIS%IDRNPB
    NNPDRN=>THIS%NNPDRN
    DRNAUX=>THIS%DRNAUX
    DRAI=>THIS%DRAI
  END SUBROUTINE PNTSET
END MODULE GWFDRNMODULE
