MODULE GWFGHBMODULE
  IMPLICIT NONE
  INTEGER,SAVE,POINTER :: NBOUND
  INTEGER,SAVE,POINTER :: MXBND
  INTEGER,SAVE,POINTER :: NGHBVL
  INTEGER,SAVE,POINTER :: IGHBCB
  INTEGER,SAVE,POINTER :: IPRGHB
  INTEGER,SAVE,POINTER :: NPGHB
  INTEGER,SAVE,POINTER :: IGHBPB
  INTEGER,SAVE,POINTER :: NNPGHB
  CHARACTER(LEN=16),SAVE,DIMENSION(:),POINTER :: GHBAUX
  REAL,SAVE,DIMENSION(:,:),POINTER :: BNDS
  TYPE :: GWFGHBTYPE
    INTEGER,POINTER :: NBOUND
    INTEGER,POINTER :: MXBND
    INTEGER,POINTER :: NGHBVL
    INTEGER,POINTER :: IGHBCB
    INTEGER,POINTER :: IPRGHB
    INTEGER,POINTER :: NPGHB
    INTEGER,POINTER :: IGHBPB
    INTEGER,POINTER :: NNPGHB
    CHARACTER(LEN=16),DIMENSION(:),POINTER :: GHBAUX
    REAL,DIMENSION(:,:),POINTER :: BNDS
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE GWFGHBTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(GWFGHBTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%NBOUND)
    DEALLOCATE(THIS%MXBND)
    DEALLOCATE(THIS%NGHBVL)
    DEALLOCATE(THIS%IGHBCB)
    DEALLOCATE(THIS%IPRGHB)
    DEALLOCATE(THIS%NPGHB)
    DEALLOCATE(THIS%IGHBPB)
    DEALLOCATE(THIS%NNPGHB)
    DEALLOCATE(THIS%GHBAUX)
    DEALLOCATE(THIS%BNDS)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(GWFGHBTYPE),INTENT(INOUT) :: THIS
    THIS%NBOUND=>NBOUND
    THIS%MXBND=>MXBND
    THIS%NGHBVL=>NGHBVL
    THIS%IGHBCB=>IGHBCB
    THIS%IPRGHB=>IPRGHB
    THIS%NPGHB=>NPGHB
    THIS%IGHBPB=>IGHBPB
    THIS%NNPGHB=>NNPGHB
    THIS%GHBAUX=>GHBAUX
    THIS%BNDS=>BNDS
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(GWFGHBTYPE),INTENT(INOUT) :: THIS
    NBOUND=>THIS%NBOUND
    MXBND=>THIS%MXBND
    NGHBVL=>THIS%NGHBVL
    IGHBCB=>THIS%IGHBCB
    IPRGHB=>THIS%IPRGHB
    NPGHB=>THIS%NPGHB
    IGHBPB=>THIS%IGHBPB
    NNPGHB=>THIS%NNPGHB
    GHBAUX=>THIS%GHBAUX
    BNDS=>THIS%BNDS
  END SUBROUTINE PNTSET
END MODULE GWFGHBMODULE
