MODULE GWFBCFMODULE
  IMPLICIT NONE
  INTEGER,SAVE,POINTER :: IBCFCB
  INTEGER,SAVE,POINTER :: IWDFLG
  INTEGER,SAVE,POINTER :: IWETIT
  INTEGER,SAVE,POINTER :: IHDWET
  INTEGER,SAVE,POINTER :: IKCFLAG
  INTEGER,SAVE,POINTER :: IKVFLAG
  REAL,SAVE,POINTER :: WETFCT
  REAL,SAVE,POINTER :: HDRY
  INTEGER,SAVE,POINTER,DIMENSION(:) :: LAYCON
  INTEGER,SAVE,POINTER,DIMENSION(:) :: LAYAVG
  REAL,SAVE,POINTER,DIMENSION(:) :: CV
  REAL,SAVE,POINTER,DIMENSION(:) :: SC1
  REAL,SAVE,POINTER,DIMENSION(:) :: SC2
  REAL,SAVE,POINTER,DIMENSION(:) :: WETDRY
  REAL,SAVE,POINTER,DIMENSION(:) :: ALPHA
  REAL,SAVE,POINTER,DIMENSION(:) :: BETA
  REAL,SAVE,POINTER,DIMENSION(:) :: SR
  REAL,SAVE,POINTER,DIMENSION(:) :: BROOK
  INTEGER,SAVE,POINTER,DIMENSION(:) :: LAYWET
  INTEGER,SAVE,POINTER :: ISFAC
  INTEGER,SAVE,POINTER :: ITHFLG
  INTEGER,SAVE,POINTER :: IHANISO
  INTEGER,SAVE,POINTER,DIMENSION(:) :: LAYTYP
  REAL,SAVE,POINTER,DIMENSION(:) :: CHANI
  INTEGER,SAVE,POINTER,DIMENSION(:) :: LAYVKA
  INTEGER,SAVE,POINTER,DIMENSION(:) :: LAYSTRT
  INTEGER,SAVE,POINTER,DIMENSION(:,:) :: LAYFLG
  REAL,SAVE,POINTER,DIMENSION(:) :: VKA
  REAL,SAVE,POINTER,DIMENSION(:) :: VKCB
  REAL,SAVE,POINTER,DIMENSION(:) :: HANI
  REAL,SAVE,POINTER,DIMENSION(:) :: HK
  DOUBLE PRECISION,SAVE,POINTER,DIMENSION(:) :: HWADIGW
  DOUBLE PRECISION,SAVE,POINTER,DIMENSION(:) :: DWADIGW
  TYPE :: GWFBCFTYPE
    INTEGER,POINTER :: IBCFCB
    INTEGER,POINTER :: IWDFLG
    INTEGER,POINTER :: IWETIT
    INTEGER,POINTER :: IHDWET
    INTEGER,POINTER :: IKCFLAG
    INTEGER,POINTER :: IKVFLAG
    REAL,POINTER :: WETFCT
    REAL,POINTER :: HDRY
    INTEGER,POINTER,DIMENSION(:) :: LAYCON
    INTEGER,POINTER,DIMENSION(:) :: LAYAVG
    REAL,POINTER,DIMENSION(:) :: CV
    REAL,POINTER,DIMENSION(:) :: SC1
    REAL,POINTER,DIMENSION(:) :: SC2
    REAL,POINTER,DIMENSION(:) :: WETDRY
    REAL,POINTER,DIMENSION(:) :: ALPHA
    REAL,POINTER,DIMENSION(:) :: BETA
    REAL,POINTER,DIMENSION(:) :: SR
    REAL,POINTER,DIMENSION(:) :: BROOK
    INTEGER,POINTER,DIMENSION(:) :: LAYWET
    INTEGER,POINTER :: ISFAC
    INTEGER,POINTER :: ITHFLG
    INTEGER,POINTER :: IHANISO
    INTEGER,POINTER,DIMENSION(:) :: LAYTYP
    REAL,POINTER,DIMENSION(:) :: CHANI
    INTEGER,POINTER,DIMENSION(:) :: LAYVKA
    INTEGER,POINTER,DIMENSION(:) :: LAYSTRT
    INTEGER,POINTER,DIMENSION(:,:) :: LAYFLG
    REAL,POINTER,DIMENSION(:) :: VKA
    REAL,POINTER,DIMENSION(:) :: VKCB
    REAL,POINTER,DIMENSION(:) :: HANI
    REAL,POINTER,DIMENSION(:) :: HK
    DOUBLE PRECISION,POINTER,DIMENSION(:) :: HWADIGW
    DOUBLE PRECISION,POINTER,DIMENSION(:) :: DWADIGW
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE GWFBCFTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(GWFBCFTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%IBCFCB)
    DEALLOCATE(THIS%IWDFLG)
    DEALLOCATE(THIS%IWETIT)
    DEALLOCATE(THIS%IHDWET)
    DEALLOCATE(THIS%IKCFLAG)
    DEALLOCATE(THIS%IKVFLAG)
    DEALLOCATE(THIS%WETFCT)
    DEALLOCATE(THIS%HDRY)
    DEALLOCATE(THIS%LAYCON)
    DEALLOCATE(THIS%LAYAVG)
    DEALLOCATE(THIS%CV)
    DEALLOCATE(THIS%SC1)
    DEALLOCATE(THIS%SC2)
    DEALLOCATE(THIS%WETDRY)
    DEALLOCATE(THIS%ALPHA)
    DEALLOCATE(THIS%BETA)
    DEALLOCATE(THIS%SR)
    DEALLOCATE(THIS%BROOK)
    DEALLOCATE(THIS%LAYWET)
    DEALLOCATE(THIS%ISFAC)
    DEALLOCATE(THIS%ITHFLG)
    DEALLOCATE(THIS%IHANISO)
    DEALLOCATE(THIS%LAYTYP)
    DEALLOCATE(THIS%CHANI)
    DEALLOCATE(THIS%LAYVKA)
    DEALLOCATE(THIS%LAYSTRT)
    DEALLOCATE(THIS%LAYFLG)
    DEALLOCATE(THIS%VKA)
    DEALLOCATE(THIS%VKCB)
    DEALLOCATE(THIS%HANI)
    DEALLOCATE(THIS%HK)
    DEALLOCATE(THIS%HWADIGW)
    DEALLOCATE(THIS%DWADIGW)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(GWFBCFTYPE),INTENT(INOUT) :: THIS
    THIS%IBCFCB=>IBCFCB
    THIS%IWDFLG=>IWDFLG
    THIS%IWETIT=>IWETIT
    THIS%IHDWET=>IHDWET
    THIS%IKCFLAG=>IKCFLAG
    THIS%IKVFLAG=>IKVFLAG
    THIS%WETFCT=>WETFCT
    THIS%HDRY=>HDRY
    THIS%LAYCON=>LAYCON
    THIS%LAYAVG=>LAYAVG
    THIS%CV=>CV
    THIS%SC1=>SC1
    THIS%SC2=>SC2
    THIS%WETDRY=>WETDRY
    THIS%ALPHA=>ALPHA
    THIS%BETA=>BETA
    THIS%SR=>SR
    THIS%BROOK=>BROOK
    THIS%LAYWET=>LAYWET
    THIS%ISFAC=>ISFAC
    THIS%ITHFLG=>ITHFLG
    THIS%IHANISO=>IHANISO
    THIS%LAYTYP=>LAYTYP
    THIS%CHANI=>CHANI
    THIS%LAYVKA=>LAYVKA
    THIS%LAYSTRT=>LAYSTRT
    THIS%LAYFLG=>LAYFLG
    THIS%VKA=>VKA
    THIS%VKCB=>VKCB
    THIS%HANI=>HANI
    THIS%HK=>HK
    THIS%HWADIGW=>HWADIGW
    THIS%DWADIGW=>DWADIGW
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(GWFBCFTYPE),INTENT(INOUT) :: THIS
    IBCFCB=>THIS%IBCFCB
    IWDFLG=>THIS%IWDFLG
    IWETIT=>THIS%IWETIT
    IHDWET=>THIS%IHDWET
    IKCFLAG=>THIS%IKCFLAG
    IKVFLAG=>THIS%IKVFLAG
    WETFCT=>THIS%WETFCT
    HDRY=>THIS%HDRY
    LAYCON=>THIS%LAYCON
    LAYAVG=>THIS%LAYAVG
    CV=>THIS%CV
    SC1=>THIS%SC1
    SC2=>THIS%SC2
    WETDRY=>THIS%WETDRY
    ALPHA=>THIS%ALPHA
    BETA=>THIS%BETA
    SR=>THIS%SR
    BROOK=>THIS%BROOK
    LAYWET=>THIS%LAYWET
    ISFAC=>THIS%ISFAC
    ITHFLG=>THIS%ITHFLG
    IHANISO=>THIS%IHANISO
    LAYTYP=>THIS%LAYTYP
    CHANI=>THIS%CHANI
    LAYVKA=>THIS%LAYVKA
    LAYSTRT=>THIS%LAYSTRT
    LAYFLG=>THIS%LAYFLG
    VKA=>THIS%VKA
    VKCB=>THIS%VKCB
    HANI=>THIS%HANI
    HK=>THIS%HK
    HWADIGW=>THIS%HWADIGW
    DWADIGW=>THIS%DWADIGW
  END SUBROUTINE PNTSET
END MODULE GWFBCFMODULE
