MODULE GWFFHBMODULE
  IMPLICIT NONE
  INTEGER,SAVE,POINTER :: NBDTIM
  INTEGER,SAVE,POINTER :: NFLW
  INTEGER,SAVE,POINTER :: NHED
  INTEGER,SAVE,POINTER :: IFHBCB
  INTEGER,SAVE,POINTER :: NFHBX1
  INTEGER,SAVE,POINTER :: NFHBX2
  INTEGER,SAVE,POINTER :: IFHBSS
  INTEGER,SAVE,POINTER,DIMENSION(:,:) :: IFLLOC
  INTEGER,SAVE,POINTER,DIMENSION(:,:) :: IHDLOC
  REAL,SAVE,POINTER,DIMENSION(:) :: BDTIM
  REAL,SAVE,POINTER,DIMENSION(:,:) :: FLWRAT
  REAL,SAVE,POINTER,DIMENSION(:,:) :: SBHED
  REAL,SAVE,POINTER,DIMENSION(:,:) :: BDFV
  REAL,SAVE,POINTER,DIMENSION(:,:) :: BDHV
  REAL,SAVE,POINTER,DIMENSION(:) :: FHBXWT
  CHARACTER(LEN=16),SAVE,POINTER,DIMENSION(:) :: FHBXNM
  TYPE :: GWFFHBTYPE
    INTEGER,POINTER :: NBDTIM
    INTEGER,POINTER :: NFLW
    INTEGER,POINTER :: NHED
    INTEGER,POINTER :: IFHBCB
    INTEGER,POINTER :: NFHBX1
    INTEGER,POINTER :: NFHBX2
    INTEGER,POINTER :: IFHBSS
    INTEGER,POINTER,DIMENSION(:,:) :: IFLLOC
    INTEGER,POINTER,DIMENSION(:,:) :: IHDLOC
    REAL,POINTER,DIMENSION(:) :: BDTIM
    REAL,POINTER,DIMENSION(:,:) :: FLWRAT
    REAL,POINTER,DIMENSION(:,:) :: SBHED
    REAL,POINTER,DIMENSION(:,:) :: BDFV
    REAL,POINTER,DIMENSION(:,:) :: BDHV
    REAL,POINTER,DIMENSION(:) :: FHBXWT
    CHARACTER(LEN=16),POINTER,DIMENSION(:) :: FHBXNM
  CONTAINS
    PROCEDURE :: DESTROY
    PROCEDURE :: PNTSAV
    PROCEDURE :: PNTSET
  END TYPE GWFFHBTYPE
  CONTAINS
  SUBROUTINE DESTROY(THIS)
    IMPLICIT NONE
    CLASS(GWFFHBTYPE),INTENT(INOUT) :: THIS
    DEALLOCATE(THIS%NBDTIM)
    DEALLOCATE(THIS%NFLW)
    DEALLOCATE(THIS%NHED)
    DEALLOCATE(THIS%IFHBCB)
    DEALLOCATE(THIS%NFHBX1)
    DEALLOCATE(THIS%NFHBX2)
    DEALLOCATE(THIS%IFHBSS)
    DEALLOCATE(THIS%IFLLOC)
    DEALLOCATE(THIS%IHDLOC)
    DEALLOCATE(THIS%BDTIM)
    DEALLOCATE(THIS%FLWRAT)
    DEALLOCATE(THIS%SBHED)
    DEALLOCATE(THIS%BDFV)
    DEALLOCATE(THIS%BDHV)
    DEALLOCATE(THIS%FHBXWT)
    DEALLOCATE(THIS%FHBXNM)
  END SUBROUTINE DESTROY
  SUBROUTINE PNTSAV(THIS)
    IMPLICIT NONE
    CLASS(GWFFHBTYPE),INTENT(INOUT) :: THIS
    THIS%NBDTIM=>NBDTIM
    THIS%NFLW=>NFLW
    THIS%NHED=>NHED
    THIS%IFHBCB=>IFHBCB
    THIS%NFHBX1=>NFHBX1
    THIS%NFHBX2=>NFHBX2
    THIS%IFHBSS=>IFHBSS
    THIS%IFLLOC=>IFLLOC
    THIS%IHDLOC=>IHDLOC
    THIS%BDTIM=>BDTIM
    THIS%FLWRAT=>FLWRAT
    THIS%SBHED=>SBHED
    THIS%BDFV=>BDFV
    THIS%BDHV=>BDHV
    THIS%FHBXWT=>FHBXWT
    THIS%FHBXNM=>FHBXNM
  END SUBROUTINE PNTSAV
  SUBROUTINE PNTSET(THIS)
    IMPLICIT NONE
    CLASS(GWFFHBTYPE),INTENT(INOUT) :: THIS
    NBDTIM=>THIS%NBDTIM
    NFLW=>THIS%NFLW
    NHED=>THIS%NHED
    IFHBCB=>THIS%IFHBCB
    NFHBX1=>THIS%NFHBX1
    NFHBX2=>THIS%NFHBX2
    IFHBSS=>THIS%IFHBSS
    IFLLOC=>THIS%IFLLOC
    IHDLOC=>THIS%IHDLOC
    BDTIM=>THIS%BDTIM
    FLWRAT=>THIS%FLWRAT
    SBHED=>THIS%SBHED
    BDFV=>THIS%BDFV
    BDHV=>THIS%BDHV
    FHBXWT=>THIS%FHBXWT
    FHBXNM=>THIS%FHBXNM
  END SUBROUTINE PNTSET
END MODULE GWFFHBMODULE
