      MODULE GLOBAL
        PARAMETER(NIUNIT=100)
        integer,save,pointer::iunsat
        INTEGER,SAVE,POINTER ::NCOL,NROW,NLAY,NPER,NBOTM,NCNFBD,IVSD
        INTEGER, SAVE, POINTER ::ITMUNI,LENUNI,IXSEC,ITRSS,INBAS,IUNSTR
        INTEGER, SAVE, POINTER :: IDEALLOC_LPF,IDEALLOC_HY,ISYMFLG
        INTEGER, SAVE, POINTER :: ITRNSP,NEQS,NODES,NJA,NJAS,NJAG
        INTEGER, SAVE, POINTER :: IOUT,IPRCONN,IDSYMRD,ILAYCON4,IWADI,IWADICLN
        INTEGER, SAVE, POINTER :: INCLN,INGNC,INGNC2,INGNCn
        INTEGER, SAVE,POINTER ::IFREFM,MXNODLAY,NOCVCO,ICONCV,NOVFC
        DOUBLE PRECISION, SAVE, POINTER::WADIEPS
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::IUNIT(:)
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::IBOUND
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::IA
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::IAG
        REAL, DIMENSION(:),ALLOCATABLE  ::FLOWJA(:)
        INTEGER, POINTER, DIMENSION(:) :: IATMP
        INTEGER, POINTER :: NJATMP
        INTEGER, SAVE,    DIMENSION(:), POINTER  ::JA
        INTEGER, SAVE,    DIMENSION(:), POINTER ::JAFL          
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::JAS
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::ISYM
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::IVC
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::HOLD
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::HNEW
        DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE ::RHS
        DOUBLE PRECISION, SAVE, DIMENSION(:), POINTER ::AMAT
        DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE ::Sn,So
        DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE ::AKRC,AKR
        REAL, DIMENSION(:),ALLOCATABLE  ::DELR
        REAL, DIMENSION(:),ALLOCATABLE  ::DELC
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::BOT
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::TOP
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::PGF
        REAL, SAVE, DIMENSION(:),ALLOCATABLE  ::AREA
        REAL, SAVE, DIMENSION(:),ALLOCATABLE  ::FAHL        
        REAL, SAVE, DIMENSION(:),ALLOCATABLE  ::CL1,CL2
        REAL, SAVE, DIMENSION(:),ALLOCATABLE  ::ARAD
        INTEGER, SAVE,    DIMENSION(:),    ALLOCATABLE  ::NODLAY
        INTEGER, DIMENSION(:),    ALLOCATABLE  ::LAYCBD
        INTEGER, SAVE,    DIMENSION(:),    ALLOCATABLE  ::LAYHDT
        INTEGER, SAVE,    DIMENSION(:),    ALLOCATABLE  ::LAYHDS
        REAL,    SAVE,    DIMENSION(:),    ALLOCATABLE  ::PERLEN
        INTEGER, SAVE,    DIMENSION(:),    ALLOCATABLE  ::NSTP
        REAL,    SAVE,    DIMENSION(:),    ALLOCATABLE  ::TSMULT
        INTEGER, SAVE,    DIMENSION(:),    ALLOCATABLE  ::ISSFLG
        REAL,    SAVE,    DIMENSION(:),ALLOCATABLE  ::BUFF
        REAL,    SAVE,    DIMENSION(:),ALLOCATABLE  ::STRT
        DOUBLE PRECISION,  SAVE,  ALLOCATABLE,   DIMENSION(:) ::HWADI
        DOUBLE PRECISION,  SAVE,  ALLOCATABLE,   DIMENSION(:) ::DWADI
    TYPE :: GWFGLOBALTYPE
        integer,pointer::iunsat
        INTEGER,POINTER ::NCOL,NROW,NLAY,NPER,NBOTM,NCNFBD,IVSD
        INTEGER,  POINTER ::ITMUNI,LENUNI,IXSEC,ITRSS,INBAS,IUNSTR
        INTEGER,  POINTER :: IDEALLOC_LPF,IDEALLOC_HY,ISYMFLG
        INTEGER,  POINTER :: ITRNSP,NEQS,NODES,NJA,NJAS,NJAG
        INTEGER,  POINTER :: IOUT,IPRCONN,IDSYMRD,ILAYCON4,IWADI,IWADICLN
        INTEGER,  POINTER :: INCLN,INGNC,INGNC2,INGNCn
        INTEGER, POINTER ::IFREFM,MXNODLAY,NOCVCO,ICONCV,NOVFC
        DOUBLE PRECISION,  POINTER::WADIEPS
        INTEGER,     DIMENSION(:),ALLOCATABLE  ::IUNIT(:)
        INTEGER,     DIMENSION(:),ALLOCATABLE  ::IBOUND
        INTEGER,     DIMENSION(:),POINTER  ::IA
        INTEGER,     DIMENSION(:),POINTER  ::IAG
        REAL, DIMENSION(:),ALLOCATABLE  ::FLOWJA(:)
        INTEGER, POINTER, DIMENSION(:) :: IATMP
        INTEGER, POINTER :: NJATMP
        INTEGER,     DIMENSION(:), POINTER  ::JA
        INTEGER,     DIMENSION(:), POINTER ::JAFL          
        INTEGER,     DIMENSION(:),ALLOCATABLE  ::JAS
        INTEGER,     DIMENSION(:),ALLOCATABLE  ::ISYM
        INTEGER,     DIMENSION(:),ALLOCATABLE  ::IVC
        DOUBLE PRECISION,  DIMENSION(:),ALLOCATABLE  ::HOLD
        DOUBLE PRECISION,  DIMENSION(:),ALLOCATABLE  ::HNEW
        DOUBLE PRECISION,  DIMENSION(:), ALLOCATABLE ::RHS
        DOUBLE PRECISION,  DIMENSION(:), POINTER ::AMAT
        DOUBLE PRECISION,  DIMENSION(:), ALLOCATABLE ::Sn,So
        DOUBLE PRECISION,  DIMENSION(:), ALLOCATABLE ::AKRC,AKR
        REAL, DIMENSION(:),ALLOCATABLE  ::DELR
        REAL, DIMENSION(:),ALLOCATABLE  ::DELC
        DOUBLE PRECISION,  DIMENSION(:),ALLOCATABLE  ::BOT
        DOUBLE PRECISION,  DIMENSION(:),ALLOCATABLE  ::TOP
        DOUBLE PRECISION,  DIMENSION(:),ALLOCATABLE  ::PGF
        REAL,  DIMENSION(:),ALLOCATABLE  ::AREA
        REAL,  DIMENSION(:),ALLOCATABLE  ::FAHL        
        REAL,  DIMENSION(:),ALLOCATABLE  ::CL1,CL2
        REAL,  DIMENSION(:),ALLOCATABLE  ::ARAD
        INTEGER,     DIMENSION(:),    ALLOCATABLE  ::NODLAY
        INTEGER, DIMENSION(:),    ALLOCATABLE  ::LAYCBD
        INTEGER,     DIMENSION(:),    ALLOCATABLE  ::LAYHDT
        INTEGER,     DIMENSION(:),    ALLOCATABLE  ::LAYHDS
        REAL,        DIMENSION(:),    ALLOCATABLE  ::PERLEN
        INTEGER,     DIMENSION(:),    ALLOCATABLE  ::NSTP
        REAL,        DIMENSION(:),    ALLOCATABLE  ::TSMULT
        INTEGER,     DIMENSION(:),    ALLOCATABLE  ::ISSFLG
        REAL,        DIMENSION(:),ALLOCATABLE  ::BUFF
        REAL,        DIMENSION(:),ALLOCATABLE  ::STRT
        DOUBLE PRECISION,    ALLOCATABLE,   DIMENSION(:) ::HWADI
        DOUBLE PRECISION,    ALLOCATABLE,   DIMENSION(:) ::DWADI
        
        CONTAINS
        
        PROCEDURE :: DESTROY => DESTROY_GWF
        PROCEDURE :: PNTSAV => PNTSAV_GWF
        PROCEDURE :: PNTSET => PNTSET_GWF
    END TYPE GWFGLOBALTYPE

    CONTAINS
    SUBROUTINE DESTROY_GWF(THIS)
      IMPLICIT NONE
      CLASS(GWFGLOBALTYPE), INTENT(INOUT) :: THIS
      !--DEALLOCATE ALLOCATED POINTERS    

    END SUBROUTINE DESTROY_GWF

    SUBROUTINE PNTSAV_GWF(THIS)
      IMPLICIT NONE
      CLASS(GWFGLOBALTYPE), INTENT(INOUT) :: THIS
      !--SAVE POINTERS
      
    END SUBROUTINE PNTSAV_GWF

    SUBROUTINE PNTSET_GWF(THIS)
      IMPLICIT NONE
      CLASS(GWFGLOBALTYPE), INTENT(INOUT) :: THIS
      !--SAVE POINTERS
      
    END SUBROUTINE PNTSET_GWF

      END MODULE GLOBAL
      