MODULE PCGUMODULE
  INTEGER, SAVE, POINTER :: ILINMETH
  INTEGER, SAVE, POINTER :: ITER1C
  INTEGER, SAVE, POINTER :: IPC
  INTEGER, SAVE, POINTER :: ISCL
  INTEGER, SAVE, POINTER :: IORD
  INTEGER, SAVE, POINTER :: ICNVGOPT
  INTEGER, SAVE, POINTER :: IACPC
  INTEGER, SAVE, POINTER :: NITERC
  INTEGER, SAVE, POINTER :: NIABCGS
  INTEGER, SAVE, POINTER :: NIAPC
  INTEGER, SAVE, POINTER :: NJAPC
  INTEGER, SAVE, POINTER :: NNZAPC
  REAL, SAVE, POINTER    :: HCLOSEPCGU
  REAL, SAVE, POINTER    :: RCLOSEPCGU
  REAL, SAVE, POINTER    :: RELAXPCGU
  DOUBLEPRECISION, SAVE, POINTER :: EPFACT
  DOUBLEPRECISION, SAVE, POINTER :: L2NORM0
!         VECTORS        
  DOUBLEPRECISION,SAVE,POINTER,DIMENSION(:),CONTIGUOUS::DSCALE
  DOUBLEPRECISION,SAVE,POINTER,DIMENSION(:),CONTIGUOUS::DSCALE2
  INTEGER,SAVE,POINTER,DIMENSION(:),CONTIGUOUS::IAPC
  INTEGER,SAVE,POINTER,DIMENSION(:),CONTIGUOUS::JAPC
  DOUBLEPRECISION,SAVE,POINTER,DIMENSION(:),CONTIGUOUS::APC
  INTEGER,SAVE,POINTER,DIMENSION(:),CONTIGUOUS::LORDER
  INTEGER,SAVE,POINTER,DIMENSION(:),CONTIGUOUS::IORDER
  INTEGER,SAVE,POINTER,DIMENSION(:),CONTIGUOUS::IARO
  INTEGER,SAVE,POINTER,DIMENSION(:),CONTIGUOUS::JARO
  DOUBLEPRECISION,SAVE,POINTER,DIMENSION(:),CONTIGUOUS::ARO
!         WORKING ARRAYS        
  INTEGER, SAVE,         POINTER, DIMENSION(:), CONTIGUOUS :: IW
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: W
  INTEGER, SAVE,         POINTER, DIMENSION(:), CONTIGUOUS :: ID
!        DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: X
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: D
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: P
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: Q
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: Z
!         BICGSTAB WORKING ARRAYS
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: T
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: V
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: DHAT
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: PHAT
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: QHAT
  ! POINTERS FOR USE WITH BOTH ORIGINAL AND RCM ORDERINGS
  INTEGER, SAVE,         POINTER, DIMENSION(:), CONTIGUOUS :: IA0
  INTEGER, SAVE,         POINTER, DIMENSION(:), CONTIGUOUS :: JA0
  DOUBLEPRECISION, SAVE, POINTER, DIMENSION(:), CONTIGUOUS :: A0
END MODULE PCGUMODULE

MODULE MPCGUCLASS
  IMPLICIT NONE
  TYPE, PUBLIC :: PCGU_DATA
    INTEGER, POINTER :: ILINMETH
    INTEGER, POINTER :: ITER1C
    INTEGER, POINTER :: IPC
    INTEGER, POINTER :: ISCL
    INTEGER, POINTER :: IORD
    INTEGER, POINTER :: ICNVGOPT
    INTEGER, POINTER :: IACPC
    INTEGER, POINTER :: NITERC
    INTEGER, POINTER :: NIABCGS
    INTEGER, POINTER :: NIAPC
    INTEGER, POINTER :: NJAPC
    INTEGER, POINTER :: NNZAPC
    REAL, POINTER    :: HCLOSEPCGU
    REAL, POINTER    :: RCLOSEPCGU
    REAL, POINTER    :: RELAXPCGU
    DOUBLEPRECISION, POINTER :: EPFACT
    DOUBLEPRECISION, POINTER :: L2NORM0
    ! VECTORS        
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::DSCALE
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::DSCALE2
    INTEGER,POINTER,DIMENSION(:),CONTIGUOUS::IAPC
    INTEGER,POINTER,DIMENSION(:),CONTIGUOUS::JAPC
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::APC
    INTEGER,POINTER,DIMENSION(:),CONTIGUOUS::LORDER
    INTEGER,POINTER,DIMENSION(:),CONTIGUOUS::IORDER
    INTEGER,POINTER,DIMENSION(:),CONTIGUOUS::IARO
    INTEGER,POINTER,DIMENSION(:),CONTIGUOUS::JARO
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::ARO
    ! WORKING ARRAYS        
    INTEGER,POINTER,DIMENSION(:),CONTIGUOUS::IW
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::W
    INTEGER,POINTER,DIMENSION(:),CONTIGUOUS::ID
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::D
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::P
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::Q
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::Z
    ! BICGSTAB WORKING ARRAYS
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::T
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::V
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::DHAT
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::PHAT
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::QHAT
    ! POINTERS FOR USE WITH BOTH ORIGINAL AND RCM ORDERINGS
    INTEGER,POINTER,DIMENSION(:),CONTIGUOUS::IA0
    INTEGER,POINTER,DIMENSION(:),CONTIGUOUS::JA0
    DOUBLEPRECISION,POINTER,DIMENSION(:),CONTIGUOUS::A0
    ! PROCEDURES (METHODS)
    CONTAINS
      PROCEDURE :: DESTROY => DESTROY_PCGU
      PROCEDURE :: PNTSAV => PNTSAV_PCGU
      PROCEDURE :: PNTSET => PNTSET_PCGU
  END TYPE PCGU_DATA
  CONTAINS
    SUBROUTINE DESTROY_PCGU(THIS)
      IMPLICIT NONE
      CLASS(PCGU_DATA), INTENT(INOUT) :: THIS
      DEALLOCATE(THIS%ILINMETH)
      DEALLOCATE(THIS%ITER1C)
      DEALLOCATE(THIS%IPC)
      DEALLOCATE(THIS%ISCL)
      DEALLOCATE(THIS%IORD)
      DEALLOCATE(THIS%ICNVGOPT)
      DEALLOCATE(THIS%IACPC)
      DEALLOCATE(THIS%NITERC)
      DEALLOCATE(THIS%NIABCGS)
      DEALLOCATE(THIS%NIAPC)
      DEALLOCATE(THIS%NJAPC)
      DEALLOCATE(THIS%NNZAPC)
      DEALLOCATE(THIS%HCLOSEPCGU)
      DEALLOCATE(THIS%RCLOSEPCGU)
      DEALLOCATE(THIS%RELAXPCGU)
      DEALLOCATE(THIS%EPFACT)
      DEALLOCATE(THIS%L2NORM0)
      DEALLOCATE(THIS%DSCALE)
      DEALLOCATE(THIS%DSCALE2)
      DEALLOCATE(THIS%IAPC)
      DEALLOCATE(THIS%JAPC)
      DEALLOCATE(THIS%APC)
      DEALLOCATE(THIS%LORDER)
      DEALLOCATE(THIS%IORDER)
      DEALLOCATE(THIS%IARO)
      DEALLOCATE(THIS%JARO)
      DEALLOCATE(THIS%ARO)
      DEALLOCATE(THIS%IW)
      DEALLOCATE(THIS%W)
      DEALLOCATE(THIS%ID)
      DEALLOCATE(THIS%D)
      DEALLOCATE(THIS%P)
      DEALLOCATE(THIS%Q)
      DEALLOCATE(THIS%Z)
      DEALLOCATE(THIS%T)
      DEALLOCATE(THIS%V)
      DEALLOCATE(THIS%DHAT)
      DEALLOCATE(THIS%PHAT)
      DEALLOCATE(THIS%QHAT)
    END SUBROUTINE DESTROY_PCGU
          
    SUBROUTINE PNTSAV_PCGU(THIS)
      USE PCGUMODULE
      IMPLICIT NONE
      CLASS(PCGU_DATA), INTENT(INOUT) :: THIS
      THIS%ILINMETH=>ILINMETH
      THIS%ITER1C=>ITER1C
      THIS%IPC=>IPC
      THIS%ISCL=>ISCL
      THIS%IORD=>IORD
      THIS%ICNVGOPT=>ICNVGOPT
      THIS%IACPC=>IACPC
      THIS%NITERC=>NITERC
      THIS%NIABCGS=>NIABCGS
      THIS%NIAPC=>NIAPC
      THIS%NJAPC=>NJAPC
      THIS%NNZAPC=>NNZAPC
      THIS%HCLOSEPCGU=>HCLOSEPCGU
      THIS%RCLOSEPCGU=>RCLOSEPCGU
      THIS%RELAXPCGU=>RELAXPCGU
      THIS%EPFACT=>EPFACT
      THIS%L2NORM0=>L2NORM0
      THIS%DSCALE=>DSCALE
      THIS%DSCALE2=>DSCALE2
      THIS%IAPC=>IAPC
      THIS%JAPC=>JAPC
      THIS%APC=>APC
      THIS%LORDER=>LORDER
      THIS%IORDER=>IORDER
      THIS%IARO=>IARO
      THIS%JARO=>JARO
      THIS%ARO=>ARO
      THIS%IW=>IW
      THIS%W=>W
      THIS%ID=>ID
      THIS%D=>D
      THIS%P=>P
      THIS%Q=>Q
      THIS%Z=>Z
      THIS%T=>T
      THIS%V=>V
      THIS%DHAT=>DHAT
      THIS%PHAT=>PHAT
      THIS%QHAT=>QHAT
      THIS%IA0=>IA0
      THIS%JA0=>JA0
      THIS%A0=>A0
    END SUBROUTINE PNTSAV_PCGU
          
    SUBROUTINE PNTSET_PCGU(THIS)
      USE PCGUMODULE
      IMPLICIT NONE
      CLASS(PCGU_DATA), INTENT(INOUT) :: THIS
      ILINMETH=>THIS%ILINMETH
      ITER1C=>THIS%ITER1C
      IPC=>THIS%IPC
      ISCL=>THIS%ISCL
      IORD=>THIS%IORD
      ICNVGOPT=>THIS%ICNVGOPT
      IACPC=>THIS%IACPC
      NITERC=>THIS%NITERC
      NIABCGS=>THIS%NIABCGS
      NIAPC=>THIS%NIAPC
      NJAPC=>THIS%NJAPC
      NNZAPC=>THIS%NNZAPC
      HCLOSEPCGU=>THIS%HCLOSEPCGU
      RCLOSEPCGU=>THIS%RCLOSEPCGU
      RELAXPCGU=>THIS%RELAXPCGU
      EPFACT=>THIS%EPFACT
      L2NORM0=>THIS%L2NORM0
      DSCALE=>THIS%DSCALE
      DSCALE2=>THIS%DSCALE2
      IAPC=>THIS%IAPC
      JAPC=>THIS%JAPC
      APC=>THIS%APC
      LORDER=>THIS%LORDER
      IORDER=>THIS%IORDER
      IARO=>THIS%IARO
      JARO=>THIS%JARO
      ARO=>THIS%ARO
      IW=>THIS%IW
      W=>THIS%W
      ID=>THIS%ID
      D=>THIS%D
      P=>THIS%P
      Q=>THIS%Q
      Z=>THIS%Z
      T=>THIS%T
      V=>THIS%V
      DHAT=>THIS%DHAT
      PHAT=>THIS%PHAT
      QHAT=>THIS%QHAT
      IA0=>THIS%IA0
      JA0=>THIS%JA0
      A0=>THIS%A0
    END SUBROUTINE PNTSET_PCGU

END MODULE MPCGUCLASS
