
MODULE SMSMODULE
  IMPLICIT NONE
  DOUBLEPRECISION, PARAMETER :: EPSILON = 1.0E-6
  DOUBLEPRECISION, PARAMETER :: CLOSEZERO = 1.0E-15      
  DOUBLEPRECISION, SAVE, POINTER :: THETA
  DOUBLEPRECISION, SAVE, POINTER :: AKAPPA
  DOUBLEPRECISION, SAVE, POINTER :: GAMMA
  DOUBLEPRECISION, SAVE, POINTER :: AMOMENTUM
  DOUBLEPRECISION, SAVE, POINTER :: BREDUC
  DOUBLEPRECISION, SAVE, POINTER :: BTOL
  DOUBLEPRECISION, SAVE, POINTER :: RES_LIM
  DOUBLEPRECISION, SAVE, DIMENSION(:), POINTER :: AMATFL
  DOUBLEPRECISION, SAVE, POINTER :: HCLOSE
  DOUBLEPRECISION, SAVE, POINTER :: HICLOSE
  DOUBLEPRECISION, SAVE, POINTER :: BIGCHOLD
  DOUBLEPRECISION, SAVE, POINTER :: BIGCH
  DOUBLEPRECISION, SAVE, POINTER :: RELAXOLD
  DOUBLEPRECISION, SAVE, POINTER :: RES_PREV
  DOUBLEPRECISION, SAVE, POINTER :: RES_NEW
  DOUBLEPRECISION, SAVE, POINTER :: RES_IN        
  INTEGER, SAVE, POINTER :: IBCOUNT
  INTEGER, SAVE, POINTER :: ICNVG
  INTEGER, SAVE, POINTER :: ITER1
  INTEGER, SAVE, POINTER :: MXITER
  INTEGER, SAVE, POINTER :: LINMETH
  INTEGER, SAVE, POINTER :: NONMETH
  INTEGER, SAVE, POINTER :: NUMTRACK
  INTEGER, SAVE, POINTER :: IPRSMS
  INTEGER, SAVE, POINTER :: IBFLAG     
  DOUBLEPRECISION, DIMENSION(:), POINTER :: HTEMP
  INTEGER, SAVE, DIMENSION(:,:), POINTER :: LRCH
  DOUBLEPRECISION, SAVE, DIMENSION(:), POINTER :: HNCG
  DOUBLEPRECISION, SAVE, DIMENSION(:), POINTER :: DEOLD
  DOUBLEPRECISION, SAVE, DIMENSION(:), POINTER :: WSAVE
  DOUBLEPRECISION, SAVE, DIMENSION(:), POINTER :: HCHOLD
  TYPE, PUBLIC :: SMS_DATA
    DOUBLEPRECISION, POINTER :: THETA
    DOUBLEPRECISION, POINTER :: AKAPPA
    DOUBLEPRECISION, POINTER :: GAMMA
    DOUBLEPRECISION, POINTER :: AMOMENTUM
    DOUBLEPRECISION, POINTER :: BREDUC
    DOUBLEPRECISION, POINTER :: BTOL
    DOUBLEPRECISION, POINTER :: RES_LIM
    DOUBLEPRECISION, DIMENSION(:), POINTER :: AMATFL
    DOUBLEPRECISION, POINTER :: HCLOSE
    DOUBLEPRECISION, POINTER :: HICLOSE
    DOUBLEPRECISION, POINTER :: BIGCHOLD
    DOUBLEPRECISION, POINTER :: BIGCH
    DOUBLEPRECISION, POINTER :: RELAXOLD
    DOUBLEPRECISION, POINTER :: RES_PREV
    DOUBLEPRECISION, POINTER :: RES_NEW
    DOUBLEPRECISION, POINTER :: RES_IN        
    INTEGER, POINTER :: IBCOUNT
    INTEGER, POINTER :: ICNVG
    INTEGER, POINTER :: ITER1
    INTEGER, POINTER :: MXITER
    INTEGER, POINTER :: LINMETH
    INTEGER, POINTER :: NONMETH
    INTEGER, POINTER :: NUMTRACK
    INTEGER, POINTER :: IPRSMS
    INTEGER, POINTER :: IBFLAG     
    DOUBLEPRECISION, DIMENSION(:), POINTER :: HTEMP
    INTEGER, DIMENSION(:,:), POINTER :: LRCH
    DOUBLEPRECISION, DIMENSION(:), POINTER :: HNCG
    DOUBLEPRECISION, DIMENSION(:), POINTER :: DEOLD
    DOUBLEPRECISION, DIMENSION(:), POINTER :: WSAVE
    DOUBLEPRECISION, DIMENSION(:), POINTER :: HCHOLD
    ! PROCEDURES (METHODS)
    CONTAINS
      PROCEDURE :: DESTROY => DESTROY_SMS
      PROCEDURE :: PNTSAV => PNTSAV_SMS
      PROCEDURE :: PNTSET => PNTSET_SMS
  END TYPE SMS_DATA

  CONTAINS
    SUBROUTINE DESTROY_SMS(THIS)
      IMPLICIT NONE
      CLASS(SMS_DATA), INTENT(INOUT) :: THIS
      !--DEALLOCATE ALLOCATED POINTERS
      IF (THIS%NONMETH.GT.0) DEALLOCATE(THIS%AMATFL)
      DEALLOCATE(THIS%THETA)
      DEALLOCATE(THIS%AKAPPA)
      DEALLOCATE(THIS%GAMMA)
      DEALLOCATE(THIS%AMOMENTUM)
      DEALLOCATE(THIS%BREDUC)
      DEALLOCATE(THIS%BTOL)
      DEALLOCATE(THIS%RES_LIM)
      DEALLOCATE(THIS%HCLOSE)
      DEALLOCATE(THIS%HICLOSE)
      DEALLOCATE(THIS%BIGCHOLD)
      DEALLOCATE(THIS%BIGCH)
      DEALLOCATE(THIS%RELAXOLD)
      DEALLOCATE(THIS%RES_PREV)
      DEALLOCATE(THIS%RES_NEW)
      DEALLOCATE(THIS%RES_IN)
      DEALLOCATE(THIS%IBCOUNT)
      DEALLOCATE(THIS%ICNVG)
      DEALLOCATE(THIS%ITER1)
      DEALLOCATE(THIS%MXITER)
      DEALLOCATE(THIS%LINMETH)
      DEALLOCATE(THIS%NONMETH)
      DEALLOCATE(THIS%NUMTRACK)
      DEALLOCATE(THIS%IPRSMS)
      DEALLOCATE(THIS%IBFLAG)    
      DEALLOCATE(THIS%HTEMP)
      DEALLOCATE(THIS%LRCH)
      DEALLOCATE(THIS%HNCG)
      DEALLOCATE(THIS%DEOLD)
      DEALLOCATE(THIS%WSAVE)
      DEALLOCATE(THIS%HCHOLD)
    END SUBROUTINE DESTROY_SMS
            
    SUBROUTINE PNTSAV_SMS(THIS)
      !USE SMSMODULE
      IMPLICIT NONE
      CLASS(SMS_DATA), INTENT(INOUT) :: THIS
      !--SAVE POINTERS
      THIS%THETA=>THETA     
      THIS%AKAPPA=>AKAPPA    
      THIS%GAMMA=>GAMMA     
      THIS%AMOMENTUM=>AMOMENTUM 
      THIS%BREDUC=>BREDUC    
      THIS%BTOL=>BTOL      
      THIS%RES_LIM=>RES_LIM   
      THIS%AMATFL=>AMATFL    
      THIS%HCLOSE=>HCLOSE    
      THIS%HICLOSE=>HICLOSE   
      THIS%BIGCHOLD=>BIGCHOLD  
      THIS%BIGCH=>BIGCH     
      THIS%RELAXOLD=>RELAXOLD
      THIS%RES_PREV=>RES_PREV
      THIS%RES_NEW=>RES_NEW
      THIS%RES_IN=>RES_IN
      THIS%IBCOUNT=>IBCOUNT
      THIS%ICNVG=>ICNVG
      THIS%ITER1=>ITER1     
      THIS%MXITER=>MXITER    
      THIS%LINMETH=>LINMETH   
      THIS%NONMETH=>NONMETH   
      THIS%NUMTRACK=>NUMTRACK  
      THIS%IPRSMS=>IPRSMS    
      THIS%IBFLAG=>IBFLAG     
      THIS%HTEMP=>HTEMP     
      THIS%LRCH=>LRCH      
      THIS%HNCG=>HNCG      
      THIS%DEOLD=>DEOLD     
      THIS%WSAVE=>WSAVE     
      THIS%HCHOLD=>HCHOLD    
    END SUBROUTINE PNTSAV_SMS

    SUBROUTINE PNTSET_SMS(THIS)
      IMPLICIT NONE
      CLASS(SMS_DATA), INTENT(INOUT) :: THIS
      !--SAVE POINTERS
      THETA=>THIS%THETA     
      AKAPPA=>THIS%AKAPPA    
      GAMMA=>THIS%GAMMA     
      AMOMENTUM=>THIS%AMOMENTUM 
      BREDUC=>THIS%BREDUC    
      BTOL=>THIS%BTOL      
      RES_LIM=>THIS%RES_LIM   
      AMATFL=>THIS%AMATFL    
      HCLOSE=>THIS%HCLOSE    
      HICLOSE=>THIS%HICLOSE   
      BIGCHOLD=>THIS%BIGCHOLD  
      BIGCH=>THIS%BIGCH     
      RELAXOLD=>THIS%RELAXOLD
      RES_PREV=>THIS%RES_PREV
      RES_NEW=>THIS%RES_NEW
      RES_IN=>THIS%RES_IN
      IBCOUNT=>THIS%IBCOUNT
      ICNVG=>THIS%ICNVG
      ITER1=>THIS%ITER1     
      MXITER=>THIS%MXITER    
      LINMETH=>THIS%LINMETH   
      NONMETH=>THIS%NONMETH   
      NUMTRACK=>THIS%NUMTRACK  
      IPRSMS=>THIS%IPRSMS    
      IBFLAG=>THIS%IBFLAG     
      HTEMP=>THIS%HTEMP     
      LRCH=>THIS%LRCH      
      HNCG=>THIS%HNCG      
      DEOLD=>THIS%DEOLD     
      WSAVE=>THIS%WSAVE     
      HCHOLD=>THIS%HCHOLD    
    END SUBROUTINE PNTSET_SMS
END MODULE SMSMODULE

