MODULE XMDMODULE
  IMPLICIT NONE
  LOGICAL, SAVE, POINTER :: REDSYS
  DOUBLEPRECISION, SAVE, POINTER :: EPSRN
  DOUBLEPRECISION, SAVE, POINTER :: RRCTOL
  DOUBLEPRECISION, SAVE, DIMENSION(:), POINTER, CONTIGUOUS :: DGSCAL
  INTEGER, SAVE, DIMENSION(:), POINTER, CONTIGUOUS :: LORDER
  INTEGER, SAVE, POINTER :: IACL
  INTEGER, SAVE, POINTER :: NORDER
  INTEGER, SAVE, POINTER :: LEVEL
  INTEGER, SAVE, POINTER :: NORTH
  INTEGER, SAVE, POINTER :: IDROPTOL
  INTEGER, SAVE, POINTER :: IERR
  INTEGER, SAVE, POINTER :: IDSCALE
END MODULE XMDMODULE

MODULE MXMDCLASS
  IMPLICIT NONE
  TYPE, PUBLIC :: XMD_DATA
    LOGICAL, POINTER :: REDSYS
    DOUBLEPRECISION, POINTER :: EPSRN
    DOUBLEPRECISION, POINTER :: RRCTOL
    DOUBLEPRECISION, DIMENSION(:), POINTER, CONTIGUOUS :: DGSCAL
    INTEGER, DIMENSION(:), POINTER, CONTIGUOUS :: LORDER
    INTEGER, POINTER :: IACL
    INTEGER, POINTER :: NORDER
    INTEGER, POINTER :: LEVEL
    INTEGER, POINTER :: NORTH
    INTEGER, POINTER :: IDROPTOL
    INTEGER, POINTER :: IERR
    INTEGER, POINTER :: IDSCALE
    ! PROCEDURES (METHODS)
    CONTAINS
      PROCEDURE :: DESTROY => DESTROY_XMD
      PROCEDURE :: PNTSAV => PNTSAV_XMD
      PROCEDURE :: PNTSET => PNTSET_XMD
  END TYPE XMD_DATA

  CONTAINS
    SUBROUTINE DESTROY_XMD(THIS)
      IMPLICIT NONE
      CLASS(XMD_DATA), INTENT(INOUT) :: THIS
      !--DEALLOCATE ALLOCATED POINTERS
      DEALLOCATE(THIS%REDSYS)
      DEALLOCATE(THIS%EPSRN)
      DEALLOCATE(THIS%RRCTOL)
      DEALLOCATE(THIS%DGSCAL)
      DEALLOCATE(THIS%LORDER)
      DEALLOCATE(THIS%IACL)
      DEALLOCATE(THIS%NORDER)
      DEALLOCATE(THIS%LEVEL)
      DEALLOCATE(THIS%NORTH)
      DEALLOCATE(THIS%IDROPTOL)
      DEALLOCATE(THIS%IERR)
      DEALLOCATE(THIS%IDSCALE)
    END SUBROUTINE DESTROY_XMD

    SUBROUTINE PNTSAV_XMD(THIS)
      USE XMDMODULE
      IMPLICIT NONE
      CLASS(XMD_DATA), INTENT(INOUT) :: THIS
      !--SAVE POINTERS
      THIS%REDSYS=>REDSYS
      THIS%EPSRN=>EPSRN
      THIS%RRCTOL=>RRCTOL
      THIS%DGSCAL=>DGSCAL
      THIS%LORDER=>LORDER
      THIS%IACL=>IACL
      THIS%NORDER=>NORDER
      THIS%LEVEL=>LEVEL
      THIS%NORTH=>NORTH
      THIS%IDROPTOL=>IDROPTOL
      THIS%IERR=>IERR
      THIS%IDSCALE=>IDSCALE
    END SUBROUTINE PNTSAV_XMD

    SUBROUTINE PNTSET_XMD(THIS)
      USE XMDMODULE
      IMPLICIT NONE
      CLASS(XMD_DATA), INTENT(INOUT) :: THIS
      !--SET POINTERS
      REDSYS=>THIS%REDSYS
      EPSRN=>THIS%EPSRN
      RRCTOL=>THIS%RRCTOL
      DGSCAL=>THIS%DGSCAL
      LORDER=>THIS%LORDER
      IACL=>THIS%IACL
      NORDER=>THIS%NORDER
      LEVEL=>THIS%LEVEL
      NORTH=>THIS%NORTH
      IDROPTOL=>THIS%IDROPTOL
      IERR=>THIS%IERR
      IDSCALE=>THIS%IDSCALE
    END SUBROUTINE PNTSET_XMD

END MODULE MXMDCLASS
